// Generated by Cadence Genus(TM) Synthesis Solution 21.17-s066_1
// Generated on: Jul  7 2025 22:23:40 EDT (Jul  8 2025 02:23:40 UTC)

// Verification Directory fv/top_level 

module tbuf(a, b, f);
  input a, b;
  output f;
  wire a, b;
  wire f;
  bufif1 fc_g1 (f, b, a);
endmodule