/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "source/conbox.sv:2.1-91.10" *)
module conbox(sb_busA, sb_busB, config_dataA, config_dataB, le_outA, le_outB, le_inA, le_inB);
  (* src = "source/conbox.sv:9.70-9.82" *)
  input [19:0] config_dataA;
  wire [19:0] config_dataA;
  (* src = "source/conbox.sv:10.70-10.82" *)
  input [19:0] config_dataB;
  wire [19:0] config_dataB;
  (* src = "source/conbox.sv:26.24-26.39" *)
  wire [3:0] \config_mux_selA[0] ;
  (* src = "source/conbox.sv:26.24-26.39" *)
  wire [3:0] \config_mux_selA[1] ;
  (* src = "source/conbox.sv:26.24-26.39" *)
  wire [3:0] \config_mux_selA[2] ;
  (* src = "source/conbox.sv:26.24-26.39" *)
  wire [3:0] \config_mux_selA[3] ;
  (* src = "source/conbox.sv:26.24-26.39" *)
  wire [3:0] \config_mux_selA[4] ;
  (* src = "source/conbox.sv:26.57-26.72" *)
  wire [3:0] \config_mux_selB[0] ;
  (* src = "source/conbox.sv:26.57-26.72" *)
  wire [3:0] \config_mux_selB[1] ;
  (* src = "source/conbox.sv:26.57-26.72" *)
  wire [3:0] \config_mux_selB[2] ;
  (* src = "source/conbox.sv:26.57-26.72" *)
  wire [3:0] \config_mux_selB[3] ;
  (* src = "source/conbox.sv:26.57-26.72" *)
  wire [3:0] \config_mux_selB[4] ;
  (* src = "source/conbox.sv:12.34-12.40" *)
  output [3:0] le_inA;
  wire [3:0] le_inA;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] le_inA_SB_LUT4_O_1_I1;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] le_inA_SB_LUT4_O_1_I1_SB_LUT4_O_1_I2;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] le_inA_SB_LUT4_O_1_I1_SB_LUT4_O_2_I2;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] le_inA_SB_LUT4_O_1_I1_SB_LUT4_O_I3;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] le_inA_SB_LUT4_O_2_I1;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] le_inA_SB_LUT4_O_2_I1_SB_LUT4_O_1_I2;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] le_inA_SB_LUT4_O_2_I1_SB_LUT4_O_2_I2;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] le_inA_SB_LUT4_O_2_I1_SB_LUT4_O_I3;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] le_inA_SB_LUT4_O_3_I1;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] le_inA_SB_LUT4_O_3_I1_SB_LUT4_O_1_I2;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] le_inA_SB_LUT4_O_3_I1_SB_LUT4_O_2_I2;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] le_inA_SB_LUT4_O_3_I1_SB_LUT4_O_I3;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] le_inA_SB_LUT4_O_I1;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] le_inA_SB_LUT4_O_I1_SB_LUT4_O_1_I2;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] le_inA_SB_LUT4_O_I1_SB_LUT4_O_2_I2;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] le_inA_SB_LUT4_O_I1_SB_LUT4_O_I3;
  (* src = "source/conbox.sv:12.42-12.48" *)
  output [3:0] le_inB;
  wire [3:0] le_inB;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] le_inB_SB_LUT4_O_1_I1;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] le_inB_SB_LUT4_O_1_I1_SB_LUT4_O_1_I2;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] le_inB_SB_LUT4_O_1_I1_SB_LUT4_O_2_I2;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] le_inB_SB_LUT4_O_1_I1_SB_LUT4_O_I3;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] le_inB_SB_LUT4_O_2_I1;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] le_inB_SB_LUT4_O_2_I1_SB_LUT4_O_1_I2;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] le_inB_SB_LUT4_O_2_I1_SB_LUT4_O_2_I2;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] le_inB_SB_LUT4_O_2_I1_SB_LUT4_O_I3;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] le_inB_SB_LUT4_O_3_I1;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] le_inB_SB_LUT4_O_3_I1_SB_LUT4_O_1_I2;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] le_inB_SB_LUT4_O_3_I1_SB_LUT4_O_2_I2;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] le_inB_SB_LUT4_O_3_I1_SB_LUT4_O_I3;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] le_inB_SB_LUT4_O_I1;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] le_inB_SB_LUT4_O_I1_SB_LUT4_O_1_I2;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] le_inB_SB_LUT4_O_I1_SB_LUT4_O_2_I2;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] le_inB_SB_LUT4_O_I1_SB_LUT4_O_I3;
  (* src = "source/conbox.sv:27.32-27.38" *)
  wire [1:0] le_out;
  (* src = "source/conbox.sv:11.34-11.41" *)
  input le_outA;
  wire le_outA;
  (* src = "source/conbox.sv:11.43-11.50" *)
  input le_outB;
  wire le_outB;
  (* src = "source/conbox.sv:28.31-28.37" *)
  wire [7:0] le_sel;
  (* src = "source/conbox.sv:81.27-81.31" *)
  wire [3:0] \output_mux[0].selA ;
  (* src = "source/conbox.sv:82.27-82.31" *)
  wire [3:0] \output_mux[0].selB ;
  (* src = "source/conbox.sv:44.27-44.34" *)
  wire [15:0] sb_bus1;
  (* src = "source/conbox.sv:45.27-45.34" *)
  wire [15:0] sb_bus2;
  (* src = "source/conbox.sv:7.26-7.33" *)
  inout [7:0] sb_busA;
  wire [7:0] sb_busA;
  wire \sb_busA_$_TBUF__Y_1_E ;
  wire \sb_busA_$_TBUF__Y_2_E ;
  wire \sb_busA_$_TBUF__Y_3_E ;
  wire \sb_busA_$_TBUF__Y_4_E ;
  wire \sb_busA_$_TBUF__Y_5_E ;
  wire \sb_busA_$_TBUF__Y_6_E ;
  wire \sb_busA_$_TBUF__Y_7_E ;
  wire \sb_busA_$_TBUF__Y_E ;
  (* src = "source/conbox.sv:8.26-8.33" *)
  inout [7:0] sb_busB;
  wire [7:0] sb_busB;
  wire \sb_busB_$_TBUF__Y_1_E ;
  wire \sb_busB_$_TBUF__Y_2_E ;
  wire \sb_busB_$_TBUF__Y_3_E ;
  wire \sb_busB_$_TBUF__Y_4_E ;
  wire \sb_busB_$_TBUF__Y_5_E ;
  wire \sb_busB_$_TBUF__Y_6_E ;
  wire \sb_busB_$_TBUF__Y_7_E ;
  wire \sb_busB_$_TBUF__Y_E ;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcccd)
  ) le_inA_SB_LUT4_O (
    .I0(config_dataA[3]),
    .I1(le_inA_SB_LUT4_O_I1[1]),
    .I2(le_inA_SB_LUT4_O_I1[2]),
    .I3(le_inA_SB_LUT4_O_I1[3]),
    .O(le_inA[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcccd)
  ) le_inA_SB_LUT4_O_1 (
    .I0(config_dataA[7]),
    .I1(le_inA_SB_LUT4_O_1_I1[1]),
    .I2(le_inA_SB_LUT4_O_1_I1[2]),
    .I3(le_inA_SB_LUT4_O_1_I1[3]),
    .O(le_inA[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hfc00)
  ) le_inA_SB_LUT4_O_1_I1_SB_LUT4_O (
    .I0(1'h0),
    .I1(config_dataA[7]),
    .I2(sb_busA[2]),
    .I3(le_inA_SB_LUT4_O_1_I1_SB_LUT4_O_I3[2]),
    .O(le_inA_SB_LUT4_O_1_I1[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8c04)
  ) le_inA_SB_LUT4_O_1_I1_SB_LUT4_O_1 (
    .I0(config_dataA[6]),
    .I1(config_dataA[4]),
    .I2(le_inA_SB_LUT4_O_1_I1_SB_LUT4_O_1_I2[2]),
    .I3(le_inA_SB_LUT4_O_1_I1_SB_LUT4_O_1_I2[3]),
    .O(le_inA_SB_LUT4_O_1_I1[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) le_inA_SB_LUT4_O_1_I1_SB_LUT4_O_1_I2_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(config_dataA[5]),
    .I3(sb_busA[6]),
    .O(le_inA_SB_LUT4_O_1_I1_SB_LUT4_O_1_I2[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0c3f)
  ) le_inA_SB_LUT4_O_1_I1_SB_LUT4_O_1_I2_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(config_dataA[5]),
    .I2(sb_busB[6]),
    .I3(sb_busB[2]),
    .O(le_inA_SB_LUT4_O_1_I1_SB_LUT4_O_1_I2[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0123)
  ) le_inA_SB_LUT4_O_1_I1_SB_LUT4_O_2 (
    .I0(config_dataA[6]),
    .I1(config_dataA[4]),
    .I2(le_inA_SB_LUT4_O_1_I1_SB_LUT4_O_2_I2[2]),
    .I3(le_inA_SB_LUT4_O_1_I1_SB_LUT4_O_2_I2[3]),
    .O(le_inA_SB_LUT4_O_1_I1[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf3c0)
  ) le_inA_SB_LUT4_O_1_I1_SB_LUT4_O_2_I2_SB_LUT4_O (
    .I0(1'h0),
    .I1(config_dataA[5]),
    .I2(sb_busA[4]),
    .I3(sb_busA[0]),
    .O(le_inA_SB_LUT4_O_1_I1_SB_LUT4_O_2_I2[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf3c0)
  ) le_inA_SB_LUT4_O_1_I1_SB_LUT4_O_2_I2_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(config_dataA[5]),
    .I2(sb_busB[4]),
    .I3(sb_busB[0]),
    .O(le_inA_SB_LUT4_O_1_I1_SB_LUT4_O_2_I2[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0300)
  ) le_inA_SB_LUT4_O_1_I1_SB_LUT4_O_I3_SB_LUT4_O (
    .I0(1'h0),
    .I1(config_dataA[6]),
    .I2(config_dataA[5]),
    .I3(config_dataA[4]),
    .O(le_inA_SB_LUT4_O_1_I1_SB_LUT4_O_I3[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcccd)
  ) le_inA_SB_LUT4_O_2 (
    .I0(config_dataA[11]),
    .I1(le_inA_SB_LUT4_O_2_I1[1]),
    .I2(le_inA_SB_LUT4_O_2_I1[2]),
    .I3(le_inA_SB_LUT4_O_2_I1[3]),
    .O(le_inA[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hfc00)
  ) le_inA_SB_LUT4_O_2_I1_SB_LUT4_O (
    .I0(1'h0),
    .I1(config_dataA[11]),
    .I2(sb_busA[2]),
    .I3(le_inA_SB_LUT4_O_2_I1_SB_LUT4_O_I3[2]),
    .O(le_inA_SB_LUT4_O_2_I1[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8c04)
  ) le_inA_SB_LUT4_O_2_I1_SB_LUT4_O_1 (
    .I0(config_dataA[10]),
    .I1(config_dataA[8]),
    .I2(le_inA_SB_LUT4_O_2_I1_SB_LUT4_O_1_I2[2]),
    .I3(le_inA_SB_LUT4_O_2_I1_SB_LUT4_O_1_I2[3]),
    .O(le_inA_SB_LUT4_O_2_I1[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) le_inA_SB_LUT4_O_2_I1_SB_LUT4_O_1_I2_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(config_dataA[9]),
    .I3(sb_busA[6]),
    .O(le_inA_SB_LUT4_O_2_I1_SB_LUT4_O_1_I2[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0c3f)
  ) le_inA_SB_LUT4_O_2_I1_SB_LUT4_O_1_I2_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(config_dataA[9]),
    .I2(sb_busB[6]),
    .I3(sb_busB[2]),
    .O(le_inA_SB_LUT4_O_2_I1_SB_LUT4_O_1_I2[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0123)
  ) le_inA_SB_LUT4_O_2_I1_SB_LUT4_O_2 (
    .I0(config_dataA[10]),
    .I1(config_dataA[8]),
    .I2(le_inA_SB_LUT4_O_2_I1_SB_LUT4_O_2_I2[2]),
    .I3(le_inA_SB_LUT4_O_2_I1_SB_LUT4_O_2_I2[3]),
    .O(le_inA_SB_LUT4_O_2_I1[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf3c0)
  ) le_inA_SB_LUT4_O_2_I1_SB_LUT4_O_2_I2_SB_LUT4_O (
    .I0(1'h0),
    .I1(config_dataA[9]),
    .I2(sb_busA[4]),
    .I3(sb_busA[0]),
    .O(le_inA_SB_LUT4_O_2_I1_SB_LUT4_O_2_I2[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf3c0)
  ) le_inA_SB_LUT4_O_2_I1_SB_LUT4_O_2_I2_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(config_dataA[9]),
    .I2(sb_busB[4]),
    .I3(sb_busB[0]),
    .O(le_inA_SB_LUT4_O_2_I1_SB_LUT4_O_2_I2[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0300)
  ) le_inA_SB_LUT4_O_2_I1_SB_LUT4_O_I3_SB_LUT4_O (
    .I0(1'h0),
    .I1(config_dataA[10]),
    .I2(config_dataA[9]),
    .I3(config_dataA[8]),
    .O(le_inA_SB_LUT4_O_2_I1_SB_LUT4_O_I3[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcccd)
  ) le_inA_SB_LUT4_O_3 (
    .I0(config_dataA[15]),
    .I1(le_inA_SB_LUT4_O_3_I1[1]),
    .I2(le_inA_SB_LUT4_O_3_I1[2]),
    .I3(le_inA_SB_LUT4_O_3_I1[3]),
    .O(le_inA[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hfc00)
  ) le_inA_SB_LUT4_O_3_I1_SB_LUT4_O (
    .I0(1'h0),
    .I1(config_dataA[15]),
    .I2(sb_busA[2]),
    .I3(le_inA_SB_LUT4_O_3_I1_SB_LUT4_O_I3[2]),
    .O(le_inA_SB_LUT4_O_3_I1[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8c04)
  ) le_inA_SB_LUT4_O_3_I1_SB_LUT4_O_1 (
    .I0(config_dataA[14]),
    .I1(config_dataA[12]),
    .I2(le_inA_SB_LUT4_O_3_I1_SB_LUT4_O_1_I2[2]),
    .I3(le_inA_SB_LUT4_O_3_I1_SB_LUT4_O_1_I2[3]),
    .O(le_inA_SB_LUT4_O_3_I1[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) le_inA_SB_LUT4_O_3_I1_SB_LUT4_O_1_I2_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(config_dataA[13]),
    .I3(sb_busA[6]),
    .O(le_inA_SB_LUT4_O_3_I1_SB_LUT4_O_1_I2[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0c3f)
  ) le_inA_SB_LUT4_O_3_I1_SB_LUT4_O_1_I2_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(config_dataA[13]),
    .I2(sb_busB[6]),
    .I3(sb_busB[2]),
    .O(le_inA_SB_LUT4_O_3_I1_SB_LUT4_O_1_I2[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0123)
  ) le_inA_SB_LUT4_O_3_I1_SB_LUT4_O_2 (
    .I0(config_dataA[14]),
    .I1(config_dataA[12]),
    .I2(le_inA_SB_LUT4_O_3_I1_SB_LUT4_O_2_I2[2]),
    .I3(le_inA_SB_LUT4_O_3_I1_SB_LUT4_O_2_I2[3]),
    .O(le_inA_SB_LUT4_O_3_I1[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf3c0)
  ) le_inA_SB_LUT4_O_3_I1_SB_LUT4_O_2_I2_SB_LUT4_O (
    .I0(1'h0),
    .I1(config_dataA[13]),
    .I2(sb_busA[4]),
    .I3(sb_busA[0]),
    .O(le_inA_SB_LUT4_O_3_I1_SB_LUT4_O_2_I2[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf3c0)
  ) le_inA_SB_LUT4_O_3_I1_SB_LUT4_O_2_I2_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(config_dataA[13]),
    .I2(sb_busB[4]),
    .I3(sb_busB[0]),
    .O(le_inA_SB_LUT4_O_3_I1_SB_LUT4_O_2_I2[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0300)
  ) le_inA_SB_LUT4_O_3_I1_SB_LUT4_O_I3_SB_LUT4_O (
    .I0(1'h0),
    .I1(config_dataA[14]),
    .I2(config_dataA[13]),
    .I3(config_dataA[12]),
    .O(le_inA_SB_LUT4_O_3_I1_SB_LUT4_O_I3[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hfc00)
  ) le_inA_SB_LUT4_O_I1_SB_LUT4_O (
    .I0(1'h0),
    .I1(config_dataA[3]),
    .I2(sb_busA[2]),
    .I3(le_inA_SB_LUT4_O_I1_SB_LUT4_O_I3[2]),
    .O(le_inA_SB_LUT4_O_I1[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8c04)
  ) le_inA_SB_LUT4_O_I1_SB_LUT4_O_1 (
    .I0(config_dataA[2]),
    .I1(config_dataA[0]),
    .I2(le_inA_SB_LUT4_O_I1_SB_LUT4_O_1_I2[2]),
    .I3(le_inA_SB_LUT4_O_I1_SB_LUT4_O_1_I2[3]),
    .O(le_inA_SB_LUT4_O_I1[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) le_inA_SB_LUT4_O_I1_SB_LUT4_O_1_I2_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(config_dataA[1]),
    .I3(sb_busA[6]),
    .O(le_inA_SB_LUT4_O_I1_SB_LUT4_O_1_I2[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0c3f)
  ) le_inA_SB_LUT4_O_I1_SB_LUT4_O_1_I2_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(config_dataA[1]),
    .I2(sb_busB[6]),
    .I3(sb_busB[2]),
    .O(le_inA_SB_LUT4_O_I1_SB_LUT4_O_1_I2[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0123)
  ) le_inA_SB_LUT4_O_I1_SB_LUT4_O_2 (
    .I0(config_dataA[2]),
    .I1(config_dataA[0]),
    .I2(le_inA_SB_LUT4_O_I1_SB_LUT4_O_2_I2[2]),
    .I3(le_inA_SB_LUT4_O_I1_SB_LUT4_O_2_I2[3]),
    .O(le_inA_SB_LUT4_O_I1[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf3c0)
  ) le_inA_SB_LUT4_O_I1_SB_LUT4_O_2_I2_SB_LUT4_O (
    .I0(1'h0),
    .I1(config_dataA[1]),
    .I2(sb_busB[4]),
    .I3(sb_busB[0]),
    .O(le_inA_SB_LUT4_O_I1_SB_LUT4_O_2_I2[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf3c0)
  ) le_inA_SB_LUT4_O_I1_SB_LUT4_O_2_I2_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(config_dataA[1]),
    .I2(sb_busA[4]),
    .I3(sb_busA[0]),
    .O(le_inA_SB_LUT4_O_I1_SB_LUT4_O_2_I2[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0300)
  ) le_inA_SB_LUT4_O_I1_SB_LUT4_O_I3_SB_LUT4_O (
    .I0(1'h0),
    .I1(config_dataA[2]),
    .I2(config_dataA[1]),
    .I3(config_dataA[0]),
    .O(le_inA_SB_LUT4_O_I1_SB_LUT4_O_I3[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcccd)
  ) le_inB_SB_LUT4_O (
    .I0(config_dataB[3]),
    .I1(le_inB_SB_LUT4_O_I1[1]),
    .I2(le_inB_SB_LUT4_O_I1[2]),
    .I3(le_inB_SB_LUT4_O_I1[3]),
    .O(le_inB[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcccd)
  ) le_inB_SB_LUT4_O_1 (
    .I0(config_dataB[7]),
    .I1(le_inB_SB_LUT4_O_1_I1[1]),
    .I2(le_inB_SB_LUT4_O_1_I1[2]),
    .I3(le_inB_SB_LUT4_O_1_I1[3]),
    .O(le_inB[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hfc00)
  ) le_inB_SB_LUT4_O_1_I1_SB_LUT4_O (
    .I0(1'h0),
    .I1(config_dataB[7]),
    .I2(sb_busA[3]),
    .I3(le_inB_SB_LUT4_O_1_I1_SB_LUT4_O_I3[2]),
    .O(le_inB_SB_LUT4_O_1_I1[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8c04)
  ) le_inB_SB_LUT4_O_1_I1_SB_LUT4_O_1 (
    .I0(config_dataB[6]),
    .I1(config_dataB[4]),
    .I2(le_inB_SB_LUT4_O_1_I1_SB_LUT4_O_1_I2[2]),
    .I3(le_inB_SB_LUT4_O_1_I1_SB_LUT4_O_1_I2[3]),
    .O(le_inB_SB_LUT4_O_1_I1[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) le_inB_SB_LUT4_O_1_I1_SB_LUT4_O_1_I2_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(config_dataB[5]),
    .I3(sb_busA[7]),
    .O(le_inB_SB_LUT4_O_1_I1_SB_LUT4_O_1_I2[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0c3f)
  ) le_inB_SB_LUT4_O_1_I1_SB_LUT4_O_1_I2_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(config_dataB[5]),
    .I2(sb_busB[7]),
    .I3(sb_busB[3]),
    .O(le_inB_SB_LUT4_O_1_I1_SB_LUT4_O_1_I2[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0123)
  ) le_inB_SB_LUT4_O_1_I1_SB_LUT4_O_2 (
    .I0(config_dataB[6]),
    .I1(config_dataB[4]),
    .I2(le_inB_SB_LUT4_O_1_I1_SB_LUT4_O_2_I2[2]),
    .I3(le_inB_SB_LUT4_O_1_I1_SB_LUT4_O_2_I2[3]),
    .O(le_inB_SB_LUT4_O_1_I1[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf3c0)
  ) le_inB_SB_LUT4_O_1_I1_SB_LUT4_O_2_I2_SB_LUT4_O (
    .I0(1'h0),
    .I1(config_dataB[5]),
    .I2(sb_busA[5]),
    .I3(sb_busA[1]),
    .O(le_inB_SB_LUT4_O_1_I1_SB_LUT4_O_2_I2[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf3c0)
  ) le_inB_SB_LUT4_O_1_I1_SB_LUT4_O_2_I2_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(config_dataB[5]),
    .I2(sb_busB[5]),
    .I3(sb_busB[1]),
    .O(le_inB_SB_LUT4_O_1_I1_SB_LUT4_O_2_I2[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0300)
  ) le_inB_SB_LUT4_O_1_I1_SB_LUT4_O_I3_SB_LUT4_O (
    .I0(1'h0),
    .I1(config_dataB[6]),
    .I2(config_dataB[5]),
    .I3(config_dataB[4]),
    .O(le_inB_SB_LUT4_O_1_I1_SB_LUT4_O_I3[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcccd)
  ) le_inB_SB_LUT4_O_2 (
    .I0(config_dataB[11]),
    .I1(le_inB_SB_LUT4_O_2_I1[1]),
    .I2(le_inB_SB_LUT4_O_2_I1[2]),
    .I3(le_inB_SB_LUT4_O_2_I1[3]),
    .O(le_inB[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hfc00)
  ) le_inB_SB_LUT4_O_2_I1_SB_LUT4_O (
    .I0(1'h0),
    .I1(config_dataB[11]),
    .I2(sb_busA[3]),
    .I3(le_inB_SB_LUT4_O_2_I1_SB_LUT4_O_I3[2]),
    .O(le_inB_SB_LUT4_O_2_I1[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8c04)
  ) le_inB_SB_LUT4_O_2_I1_SB_LUT4_O_1 (
    .I0(config_dataB[10]),
    .I1(config_dataB[8]),
    .I2(le_inB_SB_LUT4_O_2_I1_SB_LUT4_O_1_I2[2]),
    .I3(le_inB_SB_LUT4_O_2_I1_SB_LUT4_O_1_I2[3]),
    .O(le_inB_SB_LUT4_O_2_I1[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) le_inB_SB_LUT4_O_2_I1_SB_LUT4_O_1_I2_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(config_dataB[9]),
    .I3(sb_busA[7]),
    .O(le_inB_SB_LUT4_O_2_I1_SB_LUT4_O_1_I2[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0c3f)
  ) le_inB_SB_LUT4_O_2_I1_SB_LUT4_O_1_I2_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(config_dataB[9]),
    .I2(sb_busB[7]),
    .I3(sb_busB[3]),
    .O(le_inB_SB_LUT4_O_2_I1_SB_LUT4_O_1_I2[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0123)
  ) le_inB_SB_LUT4_O_2_I1_SB_LUT4_O_2 (
    .I0(config_dataB[10]),
    .I1(config_dataB[8]),
    .I2(le_inB_SB_LUT4_O_2_I1_SB_LUT4_O_2_I2[2]),
    .I3(le_inB_SB_LUT4_O_2_I1_SB_LUT4_O_2_I2[3]),
    .O(le_inB_SB_LUT4_O_2_I1[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf3c0)
  ) le_inB_SB_LUT4_O_2_I1_SB_LUT4_O_2_I2_SB_LUT4_O (
    .I0(1'h0),
    .I1(config_dataB[9]),
    .I2(sb_busA[5]),
    .I3(sb_busA[1]),
    .O(le_inB_SB_LUT4_O_2_I1_SB_LUT4_O_2_I2[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf3c0)
  ) le_inB_SB_LUT4_O_2_I1_SB_LUT4_O_2_I2_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(config_dataB[9]),
    .I2(sb_busB[5]),
    .I3(sb_busB[1]),
    .O(le_inB_SB_LUT4_O_2_I1_SB_LUT4_O_2_I2[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0300)
  ) le_inB_SB_LUT4_O_2_I1_SB_LUT4_O_I3_SB_LUT4_O (
    .I0(1'h0),
    .I1(config_dataB[10]),
    .I2(config_dataB[9]),
    .I3(config_dataB[8]),
    .O(le_inB_SB_LUT4_O_2_I1_SB_LUT4_O_I3[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcccd)
  ) le_inB_SB_LUT4_O_3 (
    .I0(config_dataB[15]),
    .I1(le_inB_SB_LUT4_O_3_I1[1]),
    .I2(le_inB_SB_LUT4_O_3_I1[2]),
    .I3(le_inB_SB_LUT4_O_3_I1[3]),
    .O(le_inB[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hfc00)
  ) le_inB_SB_LUT4_O_3_I1_SB_LUT4_O (
    .I0(1'h0),
    .I1(config_dataB[15]),
    .I2(sb_busA[3]),
    .I3(le_inB_SB_LUT4_O_3_I1_SB_LUT4_O_I3[2]),
    .O(le_inB_SB_LUT4_O_3_I1[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8c04)
  ) le_inB_SB_LUT4_O_3_I1_SB_LUT4_O_1 (
    .I0(config_dataB[14]),
    .I1(config_dataB[12]),
    .I2(le_inB_SB_LUT4_O_3_I1_SB_LUT4_O_1_I2[2]),
    .I3(le_inB_SB_LUT4_O_3_I1_SB_LUT4_O_1_I2[3]),
    .O(le_inB_SB_LUT4_O_3_I1[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) le_inB_SB_LUT4_O_3_I1_SB_LUT4_O_1_I2_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(config_dataB[13]),
    .I3(sb_busA[7]),
    .O(le_inB_SB_LUT4_O_3_I1_SB_LUT4_O_1_I2[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0c3f)
  ) le_inB_SB_LUT4_O_3_I1_SB_LUT4_O_1_I2_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(config_dataB[13]),
    .I2(sb_busB[7]),
    .I3(sb_busB[3]),
    .O(le_inB_SB_LUT4_O_3_I1_SB_LUT4_O_1_I2[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0123)
  ) le_inB_SB_LUT4_O_3_I1_SB_LUT4_O_2 (
    .I0(config_dataB[14]),
    .I1(config_dataB[12]),
    .I2(le_inB_SB_LUT4_O_3_I1_SB_LUT4_O_2_I2[2]),
    .I3(le_inB_SB_LUT4_O_3_I1_SB_LUT4_O_2_I2[3]),
    .O(le_inB_SB_LUT4_O_3_I1[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf3c0)
  ) le_inB_SB_LUT4_O_3_I1_SB_LUT4_O_2_I2_SB_LUT4_O (
    .I0(1'h0),
    .I1(config_dataB[13]),
    .I2(sb_busA[5]),
    .I3(sb_busA[1]),
    .O(le_inB_SB_LUT4_O_3_I1_SB_LUT4_O_2_I2[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf3c0)
  ) le_inB_SB_LUT4_O_3_I1_SB_LUT4_O_2_I2_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(config_dataB[13]),
    .I2(sb_busB[5]),
    .I3(sb_busB[1]),
    .O(le_inB_SB_LUT4_O_3_I1_SB_LUT4_O_2_I2[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0300)
  ) le_inB_SB_LUT4_O_3_I1_SB_LUT4_O_I3_SB_LUT4_O (
    .I0(1'h0),
    .I1(config_dataB[14]),
    .I2(config_dataB[13]),
    .I3(config_dataB[12]),
    .O(le_inB_SB_LUT4_O_3_I1_SB_LUT4_O_I3[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hfc00)
  ) le_inB_SB_LUT4_O_I1_SB_LUT4_O (
    .I0(1'h0),
    .I1(config_dataB[3]),
    .I2(sb_busA[3]),
    .I3(le_inB_SB_LUT4_O_I1_SB_LUT4_O_I3[2]),
    .O(le_inB_SB_LUT4_O_I1[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8c04)
  ) le_inB_SB_LUT4_O_I1_SB_LUT4_O_1 (
    .I0(config_dataB[2]),
    .I1(config_dataB[0]),
    .I2(le_inB_SB_LUT4_O_I1_SB_LUT4_O_1_I2[2]),
    .I3(le_inB_SB_LUT4_O_I1_SB_LUT4_O_1_I2[3]),
    .O(le_inB_SB_LUT4_O_I1[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) le_inB_SB_LUT4_O_I1_SB_LUT4_O_1_I2_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(config_dataB[1]),
    .I3(sb_busA[7]),
    .O(le_inB_SB_LUT4_O_I1_SB_LUT4_O_1_I2[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0c3f)
  ) le_inB_SB_LUT4_O_I1_SB_LUT4_O_1_I2_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(config_dataB[1]),
    .I2(sb_busB[7]),
    .I3(sb_busB[3]),
    .O(le_inB_SB_LUT4_O_I1_SB_LUT4_O_1_I2[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0123)
  ) le_inB_SB_LUT4_O_I1_SB_LUT4_O_2 (
    .I0(config_dataB[2]),
    .I1(config_dataB[0]),
    .I2(le_inB_SB_LUT4_O_I1_SB_LUT4_O_2_I2[2]),
    .I3(le_inB_SB_LUT4_O_I1_SB_LUT4_O_2_I2[3]),
    .O(le_inB_SB_LUT4_O_I1[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf3c0)
  ) le_inB_SB_LUT4_O_I1_SB_LUT4_O_2_I2_SB_LUT4_O (
    .I0(1'h0),
    .I1(config_dataB[1]),
    .I2(sb_busA[5]),
    .I3(sb_busA[1]),
    .O(le_inB_SB_LUT4_O_I1_SB_LUT4_O_2_I2[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf3c0)
  ) le_inB_SB_LUT4_O_I1_SB_LUT4_O_2_I2_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(config_dataB[1]),
    .I2(sb_busB[5]),
    .I3(sb_busB[1]),
    .O(le_inB_SB_LUT4_O_I1_SB_LUT4_O_2_I2[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0300)
  ) le_inB_SB_LUT4_O_I1_SB_LUT4_O_I3_SB_LUT4_O (
    .I0(1'h0),
    .I1(config_dataB[2]),
    .I2(config_dataB[1]),
    .I3(config_dataB[0]),
    .O(le_inB_SB_LUT4_O_I1_SB_LUT4_O_I3[2])
  );
  (* src = "source/conbox.sv:87.37-87.84" *)
  \$_TBUF_  \sb_busA_$_TBUF__Y  (
    .A(le_outB),
    .E(\sb_busA_$_TBUF__Y_E ),
    .Y(sb_busA[7])
  );
  (* src = "source/conbox.sv:86.33-86.80" *)
  \$_TBUF_  \sb_busA_$_TBUF__Y_1  (
    .A(le_outA),
    .E(\sb_busA_$_TBUF__Y_1_E ),
    .Y(sb_busA[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h1000)
  ) \sb_busA_$_TBUF__Y_1_E_SB_LUT4_O  (
    .I0(config_dataA[19]),
    .I1(config_dataA[18]),
    .I2(config_dataA[17]),
    .I3(config_dataA[16]),
    .O(\sb_busA_$_TBUF__Y_1_E )
  );
  (* src = "source/conbox.sv:87.37-87.84" *)
  \$_TBUF_  \sb_busA_$_TBUF__Y_2  (
    .A(le_outB),
    .E(\sb_busA_$_TBUF__Y_2_E ),
    .Y(sb_busA[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0010)
  ) \sb_busA_$_TBUF__Y_2_E_SB_LUT4_O  (
    .I0(config_dataB[19]),
    .I1(config_dataB[18]),
    .I2(config_dataB[17]),
    .I3(config_dataB[16]),
    .O(\sb_busA_$_TBUF__Y_2_E )
  );
  (* src = "source/conbox.sv:86.33-86.80" *)
  \$_TBUF_  \sb_busA_$_TBUF__Y_3  (
    .A(le_outA),
    .E(\sb_busA_$_TBUF__Y_3_E ),
    .Y(sb_busA[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0010)
  ) \sb_busA_$_TBUF__Y_3_E_SB_LUT4_O  (
    .I0(config_dataA[19]),
    .I1(config_dataA[18]),
    .I2(config_dataA[17]),
    .I3(config_dataA[16]),
    .O(\sb_busA_$_TBUF__Y_3_E )
  );
  (* src = "source/conbox.sv:87.37-87.84" *)
  \$_TBUF_  \sb_busA_$_TBUF__Y_4  (
    .A(le_outB),
    .E(\sb_busA_$_TBUF__Y_4_E ),
    .Y(sb_busA[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0100)
  ) \sb_busA_$_TBUF__Y_4_E_SB_LUT4_O  (
    .I0(config_dataB[19]),
    .I1(config_dataB[18]),
    .I2(config_dataB[17]),
    .I3(config_dataB[16]),
    .O(\sb_busA_$_TBUF__Y_4_E )
  );
  (* src = "source/conbox.sv:86.33-86.80" *)
  \$_TBUF_  \sb_busA_$_TBUF__Y_5  (
    .A(le_outA),
    .E(\sb_busA_$_TBUF__Y_5_E ),
    .Y(sb_busA[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0100)
  ) \sb_busA_$_TBUF__Y_5_E_SB_LUT4_O  (
    .I0(config_dataA[19]),
    .I1(config_dataA[18]),
    .I2(config_dataA[17]),
    .I3(config_dataA[16]),
    .O(\sb_busA_$_TBUF__Y_5_E )
  );
  (* src = "source/conbox.sv:87.37-87.84" *)
  \$_TBUF_  \sb_busA_$_TBUF__Y_6  (
    .A(le_outB),
    .E(\sb_busA_$_TBUF__Y_6_E ),
    .Y(sb_busA[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0001)
  ) \sb_busA_$_TBUF__Y_6_E_SB_LUT4_O  (
    .I0(config_dataB[19]),
    .I1(config_dataB[18]),
    .I2(config_dataB[17]),
    .I3(config_dataB[16]),
    .O(\sb_busA_$_TBUF__Y_6_E )
  );
  (* src = "source/conbox.sv:86.33-86.80" *)
  \$_TBUF_  \sb_busA_$_TBUF__Y_7  (
    .A(le_outA),
    .E(\sb_busA_$_TBUF__Y_7_E ),
    .Y(sb_busA[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0001)
  ) \sb_busA_$_TBUF__Y_7_E_SB_LUT4_O  (
    .I0(config_dataA[19]),
    .I1(config_dataA[18]),
    .I2(config_dataA[17]),
    .I3(config_dataA[16]),
    .O(\sb_busA_$_TBUF__Y_7_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h1000)
  ) \sb_busA_$_TBUF__Y_E_SB_LUT4_O  (
    .I0(config_dataB[19]),
    .I1(config_dataB[18]),
    .I2(config_dataB[17]),
    .I3(config_dataB[16]),
    .O(\sb_busA_$_TBUF__Y_E )
  );
  (* src = "source/conbox.sv:87.37-87.84" *)
  \$_TBUF_  \sb_busB_$_TBUF__Y  (
    .A(le_outB),
    .E(\sb_busB_$_TBUF__Y_E ),
    .Y(sb_busB[7])
  );
  (* src = "source/conbox.sv:86.33-86.80" *)
  \$_TBUF_  \sb_busB_$_TBUF__Y_1  (
    .A(le_outA),
    .E(\sb_busB_$_TBUF__Y_1_E ),
    .Y(sb_busB[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h4000)
  ) \sb_busB_$_TBUF__Y_1_E_SB_LUT4_O  (
    .I0(config_dataA[19]),
    .I1(config_dataA[18]),
    .I2(config_dataA[17]),
    .I3(config_dataA[16]),
    .O(\sb_busB_$_TBUF__Y_1_E )
  );
  (* src = "source/conbox.sv:87.37-87.84" *)
  \$_TBUF_  \sb_busB_$_TBUF__Y_2  (
    .A(le_outB),
    .E(\sb_busB_$_TBUF__Y_2_E ),
    .Y(sb_busB[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0040)
  ) \sb_busB_$_TBUF__Y_2_E_SB_LUT4_O  (
    .I0(config_dataB[19]),
    .I1(config_dataB[18]),
    .I2(config_dataB[17]),
    .I3(config_dataB[16]),
    .O(\sb_busB_$_TBUF__Y_2_E )
  );
  (* src = "source/conbox.sv:86.33-86.80" *)
  \$_TBUF_  \sb_busB_$_TBUF__Y_3  (
    .A(le_outA),
    .E(\sb_busB_$_TBUF__Y_3_E ),
    .Y(sb_busB[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0040)
  ) \sb_busB_$_TBUF__Y_3_E_SB_LUT4_O  (
    .I0(config_dataA[19]),
    .I1(config_dataA[18]),
    .I2(config_dataA[17]),
    .I3(config_dataA[16]),
    .O(\sb_busB_$_TBUF__Y_3_E )
  );
  (* src = "source/conbox.sv:87.37-87.84" *)
  \$_TBUF_  \sb_busB_$_TBUF__Y_4  (
    .A(le_outB),
    .E(\sb_busB_$_TBUF__Y_4_E ),
    .Y(sb_busB[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0400)
  ) \sb_busB_$_TBUF__Y_4_E_SB_LUT4_O  (
    .I0(config_dataB[19]),
    .I1(config_dataB[18]),
    .I2(config_dataB[17]),
    .I3(config_dataB[16]),
    .O(\sb_busB_$_TBUF__Y_4_E )
  );
  (* src = "source/conbox.sv:86.33-86.80" *)
  \$_TBUF_  \sb_busB_$_TBUF__Y_5  (
    .A(le_outA),
    .E(\sb_busB_$_TBUF__Y_5_E ),
    .Y(sb_busB[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0400)
  ) \sb_busB_$_TBUF__Y_5_E_SB_LUT4_O  (
    .I0(config_dataA[19]),
    .I1(config_dataA[18]),
    .I2(config_dataA[17]),
    .I3(config_dataA[16]),
    .O(\sb_busB_$_TBUF__Y_5_E )
  );
  (* src = "source/conbox.sv:87.37-87.84" *)
  \$_TBUF_  \sb_busB_$_TBUF__Y_6  (
    .A(le_outB),
    .E(\sb_busB_$_TBUF__Y_6_E ),
    .Y(sb_busB[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0004)
  ) \sb_busB_$_TBUF__Y_6_E_SB_LUT4_O  (
    .I0(config_dataB[19]),
    .I1(config_dataB[18]),
    .I2(config_dataB[17]),
    .I3(config_dataB[16]),
    .O(\sb_busB_$_TBUF__Y_6_E )
  );
  (* src = "source/conbox.sv:86.33-86.80" *)
  \$_TBUF_  \sb_busB_$_TBUF__Y_7  (
    .A(le_outA),
    .E(\sb_busB_$_TBUF__Y_7_E ),
    .Y(sb_busB[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0004)
  ) \sb_busB_$_TBUF__Y_7_E_SB_LUT4_O  (
    .I0(config_dataA[19]),
    .I1(config_dataA[18]),
    .I2(config_dataA[17]),
    .I3(config_dataA[16]),
    .O(\sb_busB_$_TBUF__Y_7_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h4000)
  ) \sb_busB_$_TBUF__Y_E_SB_LUT4_O  (
    .I0(config_dataB[19]),
    .I1(config_dataB[18]),
    .I2(config_dataB[17]),
    .I3(config_dataB[16]),
    .O(\sb_busB_$_TBUF__Y_E )
  );
  assign le_inA_SB_LUT4_O_I1_SB_LUT4_O_2_I2[1:0] = { config_dataA[0], config_dataA[2] };
  assign le_inB_SB_LUT4_O_3_I1[0] = config_dataB[15];
  assign le_inB_SB_LUT4_O_3_I1_SB_LUT4_O_2_I2[1:0] = { config_dataB[12], config_dataB[14] };
  assign le_inB_SB_LUT4_O_2_I1_SB_LUT4_O_2_I2[1:0] = { config_dataB[8], config_dataB[10] };
  assign le_inA_SB_LUT4_O_2_I1_SB_LUT4_O_2_I2[1:0] = { config_dataA[8], config_dataA[10] };
  assign le_inB_SB_LUT4_O_1_I1_SB_LUT4_O_1_I2[1:0] = { config_dataB[4], config_dataB[6] };
  assign le_inB_SB_LUT4_O_1_I1_SB_LUT4_O_2_I2[1:0] = { config_dataB[4], config_dataB[6] };
  assign le_inB_SB_LUT4_O_I1_SB_LUT4_O_I3[1:0] = { sb_busA[3], config_dataB[3] };
  assign le_inA_SB_LUT4_O_2_I1_SB_LUT4_O_I3[1:0] = { sb_busA[2], config_dataA[11] };
  assign le_inB_SB_LUT4_O_I1_SB_LUT4_O_1_I2[1:0] = { config_dataB[0], config_dataB[2] };
  assign le_inB_SB_LUT4_O_I1_SB_LUT4_O_2_I2[1:0] = { config_dataB[0], config_dataB[2] };
  assign le_inA_SB_LUT4_O_3_I1_SB_LUT4_O_I3[1:0] = { sb_busA[2], config_dataA[15] };
  assign le_inA_SB_LUT4_O_3_I1_SB_LUT4_O_1_I2[1:0] = { config_dataA[12], config_dataA[14] };
  assign le_inA_SB_LUT4_O_3_I1_SB_LUT4_O_2_I2[1:0] = { config_dataA[12], config_dataA[14] };
  assign le_inB_SB_LUT4_O_3_I1_SB_LUT4_O_I3[1:0] = { sb_busA[3], config_dataB[15] };
  assign le_inB_SB_LUT4_O_3_I1_SB_LUT4_O_1_I2[1:0] = { config_dataB[12], config_dataB[14] };
  assign le_inB_SB_LUT4_O_2_I1_SB_LUT4_O_I3[1:0] = { sb_busA[3], config_dataB[11] };
  assign le_inB_SB_LUT4_O_2_I1_SB_LUT4_O_1_I2[1:0] = { config_dataB[8], config_dataB[10] };
  assign le_inB_SB_LUT4_O_1_I1_SB_LUT4_O_I3[1:0] = { sb_busA[3], config_dataB[7] };
  assign le_inA_SB_LUT4_O_2_I1_SB_LUT4_O_1_I2[1:0] = { config_dataA[8], config_dataA[10] };
  assign le_inA_SB_LUT4_O_1_I1_SB_LUT4_O_I3[1:0] = { sb_busA[2], config_dataA[7] };
  assign le_inA_SB_LUT4_O_I1_SB_LUT4_O_1_I2[1:0] = { config_dataA[0], config_dataA[2] };
  assign le_inA_SB_LUT4_O_1_I1_SB_LUT4_O_1_I2[1:0] = { config_dataA[4], config_dataA[6] };
  assign le_inA_SB_LUT4_O_1_I1_SB_LUT4_O_2_I2[1:0] = { config_dataA[4], config_dataA[6] };
  assign le_inA_SB_LUT4_O_I1_SB_LUT4_O_I3[1:0] = { sb_busA[2], config_dataA[3] };
  assign le_inB_SB_LUT4_O_2_I1[0] = config_dataB[11];
  assign le_inB_SB_LUT4_O_1_I1[0] = config_dataB[7];
  assign le_inB_SB_LUT4_O_I1[0] = config_dataB[3];
  assign le_inA_SB_LUT4_O_3_I1[0] = config_dataA[15];
  assign le_inA_SB_LUT4_O_2_I1[0] = config_dataA[11];
  assign le_inA_SB_LUT4_O_1_I1[0] = config_dataA[7];
  assign le_inA_SB_LUT4_O_I1[0] = config_dataA[3];
  assign \config_mux_selA[0]  = config_dataA[3:0];
  assign \config_mux_selA[1]  = config_dataA[7:4];
  assign \config_mux_selA[2]  = config_dataA[11:8];
  assign \config_mux_selA[3]  = config_dataA[15:12];
  assign \config_mux_selA[4]  = config_dataA[19:16];
  assign \config_mux_selB[0]  = config_dataB[3:0];
  assign \config_mux_selB[1]  = config_dataB[7:4];
  assign \config_mux_selB[2]  = config_dataB[11:8];
  assign \config_mux_selB[3]  = config_dataB[15:12];
  assign \config_mux_selB[4]  = config_dataB[19:16];
  assign le_out = { le_outB, le_outA };
  assign le_sel = { le_inB[3], le_inA[3], le_inB[2], le_inA[2], le_inB[1], le_inA[1], le_inB[0], le_inA[0] };
  assign \output_mux[0].selA  = config_dataA[19:16];
  assign \output_mux[0].selB  = config_dataB[19:16];
  assign sb_bus1 = { sb_busB, sb_busA };
  assign sb_bus2 = { sb_busB, sb_busA };
endmodule
