/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module dsp(clk, config_en, nrst, config_data_in, config_data_out, config_data, in, out);
  input clk;
  wire clk;
  input config_data;
  wire config_data;
  input config_data_in;
  wire config_data_in;
  output config_data_out;
  wire config_data_out;
  input config_en;
  wire config_en;
  input [13:0] in;
  wire [13:0] in;
  input nrst;
  wire nrst;
  wire [3:0] operation;
  output [13:0] out;
  wire [13:0] out;
  wire [3:0] signed_a;
  wire [3:0] signed_b;
  wire [3:0] unsigned_a;
  wire [3:0] unsigned_b;
  assign config_data_out = 1'bx;
  assign operation = 4'bxxxx;
  assign out = { 10'b0000000000, in[3:0] };
  assign signed_a = in[3:0];
  assign signed_b = in[7:4];
  assign unsigned_a = in[3:0];
  assign unsigned_b = in[7:4];
endmodule
