/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module LE(clk, en, nrst, config_data_in, config_en, config_data_out, le_clk, le_en, le_nrst, selCB, selLEI, LEIdvn, le_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  input [3:0] LEIdvn;
  wire [3:0] LEIdvn;
  input clk;
  wire clk;
  wire [19:0] config_data;
  input config_data_in;
  wire config_data_in;
  output config_data_out;
  wire config_data_out;
  input config_en;
  wire config_en;
  wire dff0_out;
  wire dff1_out;
  wire dff_out;
  wire edge_mode;
  input en;
  wire en;
  input le_clk;
  wire le_clk;
  input le_en;
  wire le_en;
  input le_nrst;
  wire le_nrst;
  output le_out;
  wire le_out;
  wire mode;
  wire [15:0] mux_data;
  input nrst;
  wire nrst;
  wire reset_mode;
  wire reset_val;
  input [3:0] selCB;
  wire [3:0] selCB;
  input [3:0] selLEI;
  wire [3:0] selLEI;
  wire sel_clk;
  wire sel_reset;
  sky130_fd_sc_hd__clkinv_1 _055_ (
    .A(config_data[16]),
    .Y(_025_)
  );
  sky130_fd_sc_hd__mux2_1 _056_ (
    .A0(dff0_out),
    .A1(dff1_out),
    .S(config_data[18]),
    .X(dff_out)
  );
  sky130_fd_sc_hd__mux2i_1 _057_ (
    .A0(selCB[3]),
    .A1(selLEI[3]),
    .S(LEIdvn[3]),
    .Y(_026_)
  );
  sky130_fd_sc_hd__mux2i_1 _058_ (
    .A0(selCB[1]),
    .A1(selLEI[1]),
    .S(LEIdvn[1]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__mux2_1 _059_ (
    .A0(selCB[2]),
    .A1(selLEI[2]),
    .S(LEIdvn[2]),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2i_1 _060_ (
    .A0(selCB[2]),
    .A1(selLEI[2]),
    .S(LEIdvn[2]),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand2_1 _061_ (
    .A(config_data[15]),
    .B(_028_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__mux2i_1 _062_ (
    .A0(selCB[0]),
    .A1(selLEI[0]),
    .S(LEIdvn[0]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nand2_1 _063_ (
    .A(config_data[11]),
    .B(_029_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nor2_1 _064_ (
    .A(config_data[10]),
    .B(_028_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__o21ai_0 _065_ (
    .A1(config_data[14]),
    .A2(_029_),
    .B1(_031_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nor2_1 _066_ (
    .A(_033_),
    .B(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__a21oi_1 _067_ (
    .A1(_030_),
    .A2(_032_),
    .B1(_031_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand2_1 _068_ (
    .A(config_data[13]),
    .B(_028_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand2_1 _069_ (
    .A(config_data[9]),
    .B(_029_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__a21oi_1 _070_ (
    .A1(_037_),
    .A2(_038_),
    .B1(_031_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nor2_1 _071_ (
    .A(config_data[8]),
    .B(_028_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__o21ai_0 _072_ (
    .A1(config_data[12]),
    .A2(_029_),
    .B1(_031_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__o21ai_0 _073_ (
    .A1(_040_),
    .A2(_041_),
    .B1(_027_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__o32ai_1 _074_ (
    .A1(_027_),
    .A2(_035_),
    .A3(_036_),
    .B1(_039_),
    .B2(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__mux2i_1 _075_ (
    .A0(config_data[7]),
    .A1(config_data[6]),
    .S(_031_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__mux2i_1 _076_ (
    .A0(config_data[5]),
    .A1(config_data[4]),
    .S(_031_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _077_ (
    .A(_027_),
    .SLEEP(_045_),
    .X(_046_)
  );
  sky130_fd_sc_hd__o21ai_0 _078_ (
    .A1(_027_),
    .A2(_044_),
    .B1(_028_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__mux2i_1 _079_ (
    .A0(config_data[3]),
    .A1(config_data[2]),
    .S(_031_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__mux2i_1 _080_ (
    .A0(config_data[1]),
    .A1(config_data[0]),
    .S(_031_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__mux2i_1 _081_ (
    .A0(_048_),
    .A1(_049_),
    .S(_027_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__o22ai_1 _082_ (
    .A1(_046_),
    .A2(_047_),
    .B1(_050_),
    .B2(_028_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__mux2_1 _083_ (
    .A0(_043_),
    .A1(_051_),
    .S(_026_),
    .X(_052_)
  );
  sky130_fd_sc_hd__nor2_1 _084_ (
    .A(le_en),
    .B(dff_out),
    .Y(_053_)
  );
  sky130_fd_sc_hd__a21oi_1 _085_ (
    .A1(le_en),
    .A2(_052_),
    .B1(_053_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__xnor2_1 _086_ (
    .A(config_data[17]),
    .B(le_clk),
    .Y(sel_clk)
  );
  sky130_fd_sc_hd__xor2_1 _087_ (
    .A(config_data[19]),
    .B(nrst),
    .X(sel_reset)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _088_ (
    .A(nrst),
    .SLEEP(config_en),
    .X(_054_)
  );
  sky130_fd_sc_hd__o21ai_0 _089_ (
    .A1(_025_),
    .A2(dff_out),
    .B1(_054_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__a21oi_1 _090_ (
    .A1(_025_),
    .A2(_052_),
    .B1(_021_),
    .Y(le_out)
  );
  sky130_fd_sc_hd__nand2_1 _091_ (
    .A(config_en),
    .B(en),
    .Y(_022_)
  );
  sky130_fd_sc_hd__mux2_1 _092_ (
    .A0(config_data_in),
    .A1(config_data[0]),
    .S(_022_),
    .X(_001_)
  );
  sky130_fd_sc_hd__mux2_1 _093_ (
    .A0(config_data[0]),
    .A1(config_data[1]),
    .S(_022_),
    .X(_002_)
  );
  sky130_fd_sc_hd__mux2_1 _094_ (
    .A0(config_data[1]),
    .A1(config_data[2]),
    .S(_022_),
    .X(_003_)
  );
  sky130_fd_sc_hd__mux2_1 _095_ (
    .A0(config_data[2]),
    .A1(config_data[3]),
    .S(_022_),
    .X(_004_)
  );
  sky130_fd_sc_hd__mux2_1 _096_ (
    .A0(config_data[3]),
    .A1(config_data[4]),
    .S(_022_),
    .X(_005_)
  );
  sky130_fd_sc_hd__mux2_1 _097_ (
    .A0(config_data[4]),
    .A1(config_data[5]),
    .S(_022_),
    .X(_006_)
  );
  sky130_fd_sc_hd__mux2_1 _098_ (
    .A0(config_data[5]),
    .A1(config_data[6]),
    .S(_022_),
    .X(_007_)
  );
  sky130_fd_sc_hd__mux2_1 _099_ (
    .A0(config_data[6]),
    .A1(config_data[7]),
    .S(_022_),
    .X(_008_)
  );
  sky130_fd_sc_hd__mux2_1 _100_ (
    .A0(config_data[7]),
    .A1(config_data[8]),
    .S(_022_),
    .X(_009_)
  );
  sky130_fd_sc_hd__mux2_1 _101_ (
    .A0(config_data[8]),
    .A1(config_data[9]),
    .S(_022_),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux2_1 _102_ (
    .A0(config_data[9]),
    .A1(config_data[10]),
    .S(_022_),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _103_ (
    .A0(config_data[10]),
    .A1(config_data[11]),
    .S(_022_),
    .X(_012_)
  );
  sky130_fd_sc_hd__mux2_1 _104_ (
    .A0(config_data[11]),
    .A1(config_data[12]),
    .S(_022_),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _105_ (
    .A0(config_data[12]),
    .A1(config_data[13]),
    .S(_022_),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux2_1 _106_ (
    .A0(config_data[13]),
    .A1(config_data[14]),
    .S(_022_),
    .X(_015_)
  );
  sky130_fd_sc_hd__mux2_1 _107_ (
    .A0(config_data[14]),
    .A1(config_data[15]),
    .S(_022_),
    .X(_016_)
  );
  sky130_fd_sc_hd__nor2_1 _108_ (
    .A(config_data[15]),
    .B(_022_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__a21oi_1 _109_ (
    .A1(_025_),
    .A2(_022_),
    .B1(_023_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand2_1 _110_ (
    .A(config_data[17]),
    .B(_022_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__o21ai_0 _111_ (
    .A1(_025_),
    .A2(_022_),
    .B1(_024_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__mux2_1 _112_ (
    .A0(config_data[17]),
    .A1(config_data[18]),
    .S(_022_),
    .X(_019_)
  );
  sky130_fd_sc_hd__mux2_1 _113_ (
    .A0(config_data[18]),
    .A1(config_data[19]),
    .S(_022_),
    .X(_020_)
  );
  sky130_fd_sc_hd__dfrtp_1 _114_ (
    .CLK(sel_clk),
    .D(_000_),
    .Q(dff0_out),
    .RESET_B(le_nrst)
  );
  sky130_fd_sc_hd__dfstp_2 _115_ (
    .CLK(sel_clk),
    .D(_000_),
    .Q(dff1_out),
    .SET_B(le_nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _116_ (
    .CLK(clk),
    .D(_001_),
    .Q(config_data[0]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _117_ (
    .CLK(clk),
    .D(_002_),
    .Q(config_data[1]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _118_ (
    .CLK(clk),
    .D(_003_),
    .Q(config_data[2]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _119_ (
    .CLK(clk),
    .D(_004_),
    .Q(config_data[3]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _120_ (
    .CLK(clk),
    .D(_005_),
    .Q(config_data[4]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _121_ (
    .CLK(clk),
    .D(_006_),
    .Q(config_data[5]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _122_ (
    .CLK(clk),
    .D(_007_),
    .Q(config_data[6]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _123_ (
    .CLK(clk),
    .D(_008_),
    .Q(config_data[7]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _124_ (
    .CLK(clk),
    .D(_009_),
    .Q(config_data[8]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _125_ (
    .CLK(clk),
    .D(_010_),
    .Q(config_data[9]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _126_ (
    .CLK(clk),
    .D(_011_),
    .Q(config_data[10]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _127_ (
    .CLK(clk),
    .D(_012_),
    .Q(config_data[11]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _128_ (
    .CLK(clk),
    .D(_013_),
    .Q(config_data[12]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _129_ (
    .CLK(clk),
    .D(_014_),
    .Q(config_data[13]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _130_ (
    .CLK(clk),
    .D(_015_),
    .Q(config_data[14]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _131_ (
    .CLK(clk),
    .D(_016_),
    .Q(config_data[15]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _132_ (
    .CLK(clk),
    .D(_017_),
    .Q(config_data[16]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _133_ (
    .CLK(clk),
    .D(_018_),
    .Q(config_data[17]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _134_ (
    .CLK(clk),
    .D(_019_),
    .Q(config_data[18]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _135_ (
    .CLK(clk),
    .D(_020_),
    .Q(config_data[19]),
    .RESET_B(nrst)
  );
  assign config_data_out = config_data[16];
  assign edge_mode = config_data[17];
  assign mode = config_data[16];
  assign mux_data = config_data[15:0];
  assign reset_mode = config_data[19];
  assign reset_val = config_data[18];
endmodule
