/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "source/LE.sv:2.1-57.10" *)
module LE(clk, en, nrst, le_clk, le_en, le_nrst, select, config_data_in, config_data_out, le_out);
  (* src = "source/LE.sv:6.15-6.18" *)
  input clk;
  wire clk;
  (* src = "source/LE.sv:23.30-23.41" *)
  wire [16:0] config_data;
  (* src = "source/LE.sv:10.15-10.29" *)
  input config_data_in;
  wire config_data_in;
  (* src = "source/LE.sv:11.16-11.31" *)
  output config_data_out;
  wire config_data_out;
  (* src = "source/LE.sv:6.20-6.22" *)
  input en;
  wire en;
  (* src = "source/LE.sv:7.15-7.21" *)
  input le_clk;
  wire le_clk;
  (* src = "source/LE.sv:7.23-7.28" *)
  input le_en;
  wire le_en;
  (* src = "source/LE.sv:7.30-7.37" *)
  input le_nrst;
  wire le_nrst;
  wire le_nrst_SB_LUT4_I3_O;
  (* src = "source/LE.sv:12.16-12.22" *)
  output le_out;
  wire le_out;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] le_out_SB_LUT4_O_I2;
  (* src = "source/LE.sv:53.7-53.11" *)
  wire mode;
  (* src = "source/LE.sv:48.23-48.31" *)
  wire [15:0] mux_data;
  (* src = "source/LE.sv:47.7-47.14" *)
  wire mux_out;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] mux_out_SB_LUT4_O_I0;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] mux_out_SB_LUT4_O_I0_SB_LUT4_O_1_I2;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] mux_out_SB_LUT4_O_I0_SB_LUT4_O_2_I2;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] mux_out_SB_LUT4_O_I0_SB_LUT4_O_3_I1;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] mux_out_SB_LUT4_O_I0_SB_LUT4_O_I2;
  (* src = "source/LE.sv:6.24-6.28" *)
  input nrst;
  wire nrst;
  wire nrst_SB_LUT4_I3_O;
  (* src = "source/LE.sv:8.40-8.46" *)
  input [3:0] select;
  wire [3:0] select;
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "source/LE.sv:24.1-30.4|/home/shay/a/ece270/bin/../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER config_data_SB_DFFER_Q (
    .C(clk),
    .D(config_data[14]),
    .E(en),
    .Q(config_data[15]),
    .R(nrst_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "source/LE.sv:24.1-30.4|/home/shay/a/ece270/bin/../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER config_data_SB_DFFER_Q_1 (
    .C(clk),
    .D(config_data[13]),
    .E(en),
    .Q(config_data[14]),
    .R(nrst_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "source/LE.sv:24.1-30.4|/home/shay/a/ece270/bin/../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER config_data_SB_DFFER_Q_10 (
    .C(clk),
    .D(config_data[4]),
    .E(en),
    .Q(config_data[5]),
    .R(nrst_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "source/LE.sv:24.1-30.4|/home/shay/a/ece270/bin/../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER config_data_SB_DFFER_Q_11 (
    .C(clk),
    .D(config_data[3]),
    .E(en),
    .Q(config_data[4]),
    .R(nrst_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "source/LE.sv:24.1-30.4|/home/shay/a/ece270/bin/../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER config_data_SB_DFFER_Q_12 (
    .C(clk),
    .D(config_data[2]),
    .E(en),
    .Q(config_data[3]),
    .R(nrst_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "source/LE.sv:24.1-30.4|/home/shay/a/ece270/bin/../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER config_data_SB_DFFER_Q_13 (
    .C(clk),
    .D(config_data[1]),
    .E(en),
    .Q(config_data[2]),
    .R(nrst_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "source/LE.sv:24.1-30.4|/home/shay/a/ece270/bin/../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER config_data_SB_DFFER_Q_14 (
    .C(clk),
    .D(config_data[0]),
    .E(en),
    .Q(config_data[1]),
    .R(nrst_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "source/LE.sv:24.1-30.4|/home/shay/a/ece270/bin/../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER config_data_SB_DFFER_Q_15 (
    .C(clk),
    .D(config_data_in),
    .E(en),
    .Q(config_data[0]),
    .R(nrst_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "source/LE.sv:24.1-30.4|/home/shay/a/ece270/bin/../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER config_data_SB_DFFER_Q_2 (
    .C(clk),
    .D(config_data[12]),
    .E(en),
    .Q(config_data[13]),
    .R(nrst_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "source/LE.sv:24.1-30.4|/home/shay/a/ece270/bin/../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER config_data_SB_DFFER_Q_3 (
    .C(clk),
    .D(config_data[11]),
    .E(en),
    .Q(config_data[12]),
    .R(nrst_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "source/LE.sv:24.1-30.4|/home/shay/a/ece270/bin/../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER config_data_SB_DFFER_Q_4 (
    .C(clk),
    .D(config_data[10]),
    .E(en),
    .Q(config_data[11]),
    .R(nrst_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "source/LE.sv:24.1-30.4|/home/shay/a/ece270/bin/../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER config_data_SB_DFFER_Q_5 (
    .C(clk),
    .D(config_data[9]),
    .E(en),
    .Q(config_data[10]),
    .R(nrst_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "source/LE.sv:24.1-30.4|/home/shay/a/ece270/bin/../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER config_data_SB_DFFER_Q_6 (
    .C(clk),
    .D(config_data[8]),
    .E(en),
    .Q(config_data[9]),
    .R(nrst_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "source/LE.sv:24.1-30.4|/home/shay/a/ece270/bin/../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER config_data_SB_DFFER_Q_7 (
    .C(clk),
    .D(config_data[7]),
    .E(en),
    .Q(config_data[8]),
    .R(nrst_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "source/LE.sv:24.1-30.4|/home/shay/a/ece270/bin/../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER config_data_SB_DFFER_Q_8 (
    .C(clk),
    .D(config_data[6]),
    .E(en),
    .Q(config_data[7]),
    .R(nrst_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "source/LE.sv:24.1-30.4|/home/shay/a/ece270/bin/../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER config_data_SB_DFFER_Q_9 (
    .C(clk),
    .D(config_data[5]),
    .E(en),
    .Q(config_data[6]),
    .R(nrst_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "source/LE.sv:24.1-30.4|/home/shay/a/ece270/bin/../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER config_data_out_SB_DFFER_Q (
    .C(clk),
    .D(config_data[15]),
    .E(en),
    .Q(config_data_out),
    .R(nrst_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "source/LE.sv:36.1-44.4|/home/shay/a/ece270/bin/../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER le_en_SB_DFFER_E (
    .C(le_clk),
    .D(mux_out),
    .E(le_en),
    .Q(le_out_SB_LUT4_O_I2[1]),
    .R(le_nrst_SB_LUT4_I3_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:12.34-13.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) le_nrst_SB_LUT4_I3 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(le_nrst),
    .O(le_nrst_SB_LUT4_I3_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf3c0)
  ) le_out_SB_LUT4_O (
    .I0(1'h0),
    .I1(config_data_out),
    .I2(le_out_SB_LUT4_O_I2[1]),
    .I3(mux_out),
    .O(le_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h5d0c)
  ) mux_out_SB_LUT4_O (
    .I0(mux_out_SB_LUT4_O_I0[0]),
    .I1(mux_out_SB_LUT4_O_I0[1]),
    .I2(mux_out_SB_LUT4_O_I0[2]),
    .I3(mux_out_SB_LUT4_O_I0[3]),
    .O(mux_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h1115)
  ) mux_out_SB_LUT4_O_I0_SB_LUT4_O (
    .I0(select[3]),
    .I1(select[2]),
    .I2(mux_out_SB_LUT4_O_I0_SB_LUT4_O_I2[2]),
    .I3(mux_out_SB_LUT4_O_I0_SB_LUT4_O_I2[3]),
    .O(mux_out_SB_LUT4_O_I0[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0145)
  ) mux_out_SB_LUT4_O_I0_SB_LUT4_O_1 (
    .I0(select[2]),
    .I1(select[0]),
    .I2(mux_out_SB_LUT4_O_I0_SB_LUT4_O_1_I2[2]),
    .I3(mux_out_SB_LUT4_O_I0_SB_LUT4_O_1_I2[3]),
    .O(mux_out_SB_LUT4_O_I0[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf3c0)
  ) mux_out_SB_LUT4_O_I0_SB_LUT4_O_1_I2_SB_LUT4_O (
    .I0(1'h0),
    .I1(select[1]),
    .I2(config_data[2]),
    .I3(config_data[0]),
    .O(mux_out_SB_LUT4_O_I0_SB_LUT4_O_1_I2[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf3c0)
  ) mux_out_SB_LUT4_O_I0_SB_LUT4_O_1_I2_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(select[1]),
    .I2(config_data[3]),
    .I3(config_data[1]),
    .O(mux_out_SB_LUT4_O_I0_SB_LUT4_O_1_I2[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'haaa2)
  ) mux_out_SB_LUT4_O_I0_SB_LUT4_O_2 (
    .I0(select[3]),
    .I1(select[2]),
    .I2(mux_out_SB_LUT4_O_I0_SB_LUT4_O_2_I2[2]),
    .I3(mux_out_SB_LUT4_O_I0_SB_LUT4_O_2_I2[3]),
    .O(mux_out_SB_LUT4_O_I0[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h5140)
  ) mux_out_SB_LUT4_O_I0_SB_LUT4_O_2_I2_SB_LUT4_O (
    .I0(select[1]),
    .I1(select[0]),
    .I2(config_data[13]),
    .I3(config_data[12]),
    .O(mux_out_SB_LUT4_O_I0_SB_LUT4_O_2_I2[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'ha280)
  ) mux_out_SB_LUT4_O_I0_SB_LUT4_O_2_I2_SB_LUT4_O_1 (
    .I0(select[1]),
    .I1(select[0]),
    .I2(config_data[15]),
    .I3(config_data[14]),
    .O(mux_out_SB_LUT4_O_I0_SB_LUT4_O_2_I2[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0051)
  ) mux_out_SB_LUT4_O_I0_SB_LUT4_O_3 (
    .I0(select[2]),
    .I1(mux_out_SB_LUT4_O_I0_SB_LUT4_O_3_I1[1]),
    .I2(mux_out_SB_LUT4_O_I0_SB_LUT4_O_3_I1[2]),
    .I3(mux_out_SB_LUT4_O_I0_SB_LUT4_O_3_I1[3]),
    .O(mux_out_SB_LUT4_O_I0[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h00f0)
  ) mux_out_SB_LUT4_O_I0_SB_LUT4_O_3_I1_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(select[0]),
    .I3(config_data[11]),
    .O(mux_out_SB_LUT4_O_I0_SB_LUT4_O_3_I1[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h5140)
  ) mux_out_SB_LUT4_O_I0_SB_LUT4_O_3_I1_SB_LUT4_O_1 (
    .I0(select[1]),
    .I1(select[0]),
    .I2(config_data[9]),
    .I3(config_data[8]),
    .O(mux_out_SB_LUT4_O_I0_SB_LUT4_O_3_I1[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hccc0)
  ) mux_out_SB_LUT4_O_I0_SB_LUT4_O_3_I1_SB_LUT4_O_2 (
    .I0(1'h0),
    .I1(select[1]),
    .I2(select[0]),
    .I3(config_data[10]),
    .O(mux_out_SB_LUT4_O_I0_SB_LUT4_O_3_I1[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0213)
  ) mux_out_SB_LUT4_O_I0_SB_LUT4_O_I2_SB_LUT4_O (
    .I0(select[1]),
    .I1(select[0]),
    .I2(config_data[6]),
    .I3(config_data[4]),
    .O(mux_out_SB_LUT4_O_I0_SB_LUT4_O_I2[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h084c)
  ) mux_out_SB_LUT4_O_I0_SB_LUT4_O_I2_SB_LUT4_O_1 (
    .I0(select[1]),
    .I1(select[0]),
    .I2(config_data[7]),
    .I3(config_data[5]),
    .O(mux_out_SB_LUT4_O_I0_SB_LUT4_O_I2[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:12.34-13.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) nrst_SB_LUT4_I3 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(nrst),
    .O(nrst_SB_LUT4_I3_O)
  );
  assign mux_out_SB_LUT4_O_I0_SB_LUT4_O_3_I1[0] = select[2];
  assign mux_out_SB_LUT4_O_I0_SB_LUT4_O_I2[1:0] = { select[2], select[3] };
  assign mux_out_SB_LUT4_O_I0_SB_LUT4_O_2_I2[1:0] = { select[2], select[3] };
  assign mux_out_SB_LUT4_O_I0_SB_LUT4_O_1_I2[1:0] = { select[0], select[2] };
  assign { le_out_SB_LUT4_O_I2[2], le_out_SB_LUT4_O_I2[0] } = { mux_out, config_data_out };
  assign config_data[16] = config_data_out;
  assign mode = config_data_out;
  assign mux_data = config_data[15:0];
endmodule
