/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module LEI(clk, en, nrst, config_data, leout0A, leout0B, leout1A, leout1B, lein0A, lein0B, lein1A, lein1B, drvLE0A, drvLE0B, drvLE1A, drvLE1B);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  input clk;
  wire clk;
  wire [3:0] \concat_inputs[0] ;
  wire [3:0] \concat_inputs[1] ;
  wire [3:0] \concat_inputs[2] ;
  wire [3:0] \concat_inputs[3] ;
  wire \concat_outputs[0] ;
  wire \concat_outputs[1] ;
  wire \concat_outputs[2] ;
  wire \concat_outputs[3] ;
  input [47:0] config_data;
  wire [47:0] config_data;
  output [3:0] drvLE0A;
  wire [3:0] drvLE0A;
  output [3:0] drvLE0B;
  wire [3:0] drvLE0B;
  output [3:0] drvLE1A;
  wire [3:0] drvLE1A;
  output [3:0] drvLE1B;
  wire [3:0] drvLE1B;
  input en;
  wire en;
  wire [3:0] \input_drv[0] ;
  wire [3:0] \input_drv[1] ;
  wire [3:0] \input_drv[2] ;
  wire [3:0] \input_drv[3] ;
  output [3:0] lein0A;
  wire [3:0] lein0A;
  output [3:0] lein0B;
  wire [3:0] lein0B;
  output [3:0] lein1A;
  wire [3:0] lein1A;
  output [3:0] lein1B;
  wire [3:0] lein1B;
  input leout0A;
  wire leout0A;
  input leout0B;
  wire leout0B;
  input leout1A;
  wire leout1A;
  input leout1B;
  wire leout1B;
  input nrst;
  wire nrst;
  wire [31:0] \sv2v_autoblock_1.i ;
  sky130_fd_sc_hd__clkinv_1 _16_ (
    .A(config_data[8]),
    .Y(drvLE0A[2])
  );
  sky130_fd_sc_hd__clkinv_1 _17_ (
    .A(config_data[41]),
    .Y(drvLE1B[1])
  );
  sky130_fd_sc_hd__clkinv_1 _18_ (
    .A(config_data[29]),
    .Y(drvLE1A[1])
  );
  sky130_fd_sc_hd__clkinv_1 _19_ (
    .A(config_data[17]),
    .Y(drvLE0B[1])
  );
  sky130_fd_sc_hd__clkinv_1 _20_ (
    .A(config_data[5]),
    .Y(drvLE0A[1])
  );
  sky130_fd_sc_hd__clkinv_1 _21_ (
    .A(config_data[38]),
    .Y(drvLE1B[0])
  );
  sky130_fd_sc_hd__clkinv_1 _22_ (
    .A(config_data[26]),
    .Y(drvLE1A[0])
  );
  sky130_fd_sc_hd__clkinv_1 _23_ (
    .A(config_data[14]),
    .Y(drvLE0B[0])
  );
  sky130_fd_sc_hd__clkinv_1 _24_ (
    .A(config_data[2]),
    .Y(drvLE0A[0])
  );
  sky130_fd_sc_hd__clkinv_1 _25_ (
    .A(config_data[47]),
    .Y(drvLE1B[3])
  );
  sky130_fd_sc_hd__clkinv_1 _26_ (
    .A(config_data[35]),
    .Y(drvLE1A[3])
  );
  sky130_fd_sc_hd__clkinv_1 _27_ (
    .A(config_data[23]),
    .Y(drvLE0B[3])
  );
  sky130_fd_sc_hd__clkinv_1 _28_ (
    .A(config_data[11]),
    .Y(drvLE0A[3])
  );
  sky130_fd_sc_hd__clkinv_1 _29_ (
    .A(config_data[44]),
    .Y(drvLE1B[2])
  );
  sky130_fd_sc_hd__clkinv_1 _30_ (
    .A(config_data[32]),
    .Y(drvLE1A[2])
  );
  sky130_fd_sc_hd__clkinv_1 _31_ (
    .A(config_data[20]),
    .Y(drvLE0B[2])
  );
  sky130_fd_sc_hd__mux4_2 _32_ (
    .A0(leout0A),
    .A1(leout1A),
    .A2(leout0B),
    .A3(leout1B),
    .S0(config_data[7]),
    .S1(config_data[6]),
    .X(_00_)
  );
  sky130_fd_sc_hd__and2_0 _33_ (
    .A(drvLE0A[2]),
    .B(_00_),
    .X(lein0A[2])
  );
  sky130_fd_sc_hd__mux4_2 _34_ (
    .A0(leout0A),
    .A1(leout1A),
    .A2(leout0B),
    .A3(leout1B),
    .S0(config_data[40]),
    .S1(config_data[39]),
    .X(_01_)
  );
  sky130_fd_sc_hd__and2_0 _35_ (
    .A(drvLE1B[1]),
    .B(_01_),
    .X(lein1B[1])
  );
  sky130_fd_sc_hd__mux4_2 _36_ (
    .A0(leout0A),
    .A1(leout1A),
    .A2(leout0B),
    .A3(leout1B),
    .S0(config_data[28]),
    .S1(config_data[27]),
    .X(_02_)
  );
  sky130_fd_sc_hd__and2_0 _37_ (
    .A(drvLE1A[1]),
    .B(_02_),
    .X(lein1A[1])
  );
  sky130_fd_sc_hd__mux4_2 _38_ (
    .A0(leout0A),
    .A1(leout1A),
    .A2(leout0B),
    .A3(leout1B),
    .S0(config_data[16]),
    .S1(config_data[15]),
    .X(_03_)
  );
  sky130_fd_sc_hd__and2_0 _39_ (
    .A(drvLE0B[1]),
    .B(_03_),
    .X(lein0B[1])
  );
  sky130_fd_sc_hd__mux4_2 _40_ (
    .A0(leout0A),
    .A1(leout1A),
    .A2(leout0B),
    .A3(leout1B),
    .S0(config_data[4]),
    .S1(config_data[3]),
    .X(_04_)
  );
  sky130_fd_sc_hd__and2_0 _41_ (
    .A(drvLE0A[1]),
    .B(_04_),
    .X(lein0A[1])
  );
  sky130_fd_sc_hd__mux4_2 _42_ (
    .A0(leout0A),
    .A1(leout1A),
    .A2(leout0B),
    .A3(leout1B),
    .S0(config_data[37]),
    .S1(config_data[36]),
    .X(_05_)
  );
  sky130_fd_sc_hd__and2_0 _43_ (
    .A(drvLE1B[0]),
    .B(_05_),
    .X(lein1B[0])
  );
  sky130_fd_sc_hd__mux4_2 _44_ (
    .A0(leout0A),
    .A1(leout1A),
    .A2(leout0B),
    .A3(leout1B),
    .S0(config_data[25]),
    .S1(config_data[24]),
    .X(_06_)
  );
  sky130_fd_sc_hd__and2_0 _45_ (
    .A(drvLE1A[0]),
    .B(_06_),
    .X(lein1A[0])
  );
  sky130_fd_sc_hd__mux4_2 _46_ (
    .A0(leout0A),
    .A1(leout1A),
    .A2(leout0B),
    .A3(leout1B),
    .S0(config_data[13]),
    .S1(config_data[12]),
    .X(_07_)
  );
  sky130_fd_sc_hd__and2_0 _47_ (
    .A(drvLE0B[0]),
    .B(_07_),
    .X(lein0B[0])
  );
  sky130_fd_sc_hd__mux4_2 _48_ (
    .A0(leout0A),
    .A1(leout1A),
    .A2(leout0B),
    .A3(leout1B),
    .S0(config_data[1]),
    .S1(config_data[0]),
    .X(_08_)
  );
  sky130_fd_sc_hd__and2_0 _49_ (
    .A(drvLE0A[0]),
    .B(_08_),
    .X(lein0A[0])
  );
  sky130_fd_sc_hd__mux4_2 _50_ (
    .A0(leout0A),
    .A1(leout1A),
    .A2(leout0B),
    .A3(leout1B),
    .S0(config_data[46]),
    .S1(config_data[45]),
    .X(_09_)
  );
  sky130_fd_sc_hd__and2_0 _51_ (
    .A(drvLE1B[3]),
    .B(_09_),
    .X(lein1B[3])
  );
  sky130_fd_sc_hd__mux4_2 _52_ (
    .A0(leout0A),
    .A1(leout1A),
    .A2(leout0B),
    .A3(leout1B),
    .S0(config_data[34]),
    .S1(config_data[33]),
    .X(_10_)
  );
  sky130_fd_sc_hd__and2_0 _53_ (
    .A(drvLE1A[3]),
    .B(_10_),
    .X(lein1A[3])
  );
  sky130_fd_sc_hd__mux4_2 _54_ (
    .A0(leout0A),
    .A1(leout1A),
    .A2(leout0B),
    .A3(leout1B),
    .S0(config_data[22]),
    .S1(config_data[21]),
    .X(_11_)
  );
  sky130_fd_sc_hd__and2_0 _55_ (
    .A(drvLE0B[3]),
    .B(_11_),
    .X(lein0B[3])
  );
  sky130_fd_sc_hd__mux4_2 _56_ (
    .A0(leout0A),
    .A1(leout1A),
    .A2(leout0B),
    .A3(leout1B),
    .S0(config_data[10]),
    .S1(config_data[9]),
    .X(_12_)
  );
  sky130_fd_sc_hd__and2_0 _57_ (
    .A(drvLE0A[3]),
    .B(_12_),
    .X(lein0A[3])
  );
  sky130_fd_sc_hd__mux4_2 _58_ (
    .A0(leout0A),
    .A1(leout1A),
    .A2(leout0B),
    .A3(leout1B),
    .S0(config_data[43]),
    .S1(config_data[42]),
    .X(_13_)
  );
  sky130_fd_sc_hd__and2_0 _59_ (
    .A(drvLE1B[2]),
    .B(_13_),
    .X(lein1B[2])
  );
  sky130_fd_sc_hd__mux4_2 _60_ (
    .A0(leout0A),
    .A1(leout1A),
    .A2(leout0B),
    .A3(leout1B),
    .S0(config_data[31]),
    .S1(config_data[30]),
    .X(_14_)
  );
  sky130_fd_sc_hd__and2_0 _61_ (
    .A(drvLE1A[2]),
    .B(_14_),
    .X(lein1A[2])
  );
  sky130_fd_sc_hd__mux4_2 _62_ (
    .A0(leout0A),
    .A1(leout1A),
    .A2(leout0B),
    .A3(leout1B),
    .S0(config_data[19]),
    .S1(config_data[18]),
    .X(_15_)
  );
  sky130_fd_sc_hd__and2_0 _63_ (
    .A(drvLE0B[2]),
    .B(_15_),
    .X(lein0B[2])
  );
  assign \concat_inputs[0]  = lein0A;
  assign \concat_inputs[1]  = lein0B;
  assign \concat_inputs[2]  = lein1A;
  assign \concat_inputs[3]  = lein1B;
  assign \concat_outputs[0]  = leout0A;
  assign \concat_outputs[1]  = leout0B;
  assign \concat_outputs[2]  = leout1A;
  assign \concat_outputs[3]  = leout1B;
  assign \input_drv[0]  = drvLE0A;
  assign \input_drv[1]  = drvLE0B;
  assign \input_drv[2]  = drvLE1A;
  assign \input_drv[3]  = drvLE1B;
  assign \sv2v_autoblock_1.i  = 32'b00000000000000000000000000000100;
endmodule
