/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module LEI(clk, nrst, config_en, config_data_in, config_data_out, leout0A, leout0B, leout1A, leout1B, lein0A, lein0B, lein1A, lein1B);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  input clk;
  wire clk;
  wire [3:0] \concat_inputs[0] ;
  wire [3:0] \concat_inputs[1] ;
  wire [3:0] \concat_inputs[2] ;
  wire [3:0] \concat_inputs[3] ;
  wire [47:0] config_data;
  input config_data_in;
  wire config_data_in;
  output config_data_out;
  wire config_data_out;
  input config_en;
  wire config_en;
  wire [3:0] le_outputs;
  output [3:0] lein0A;
  wire [3:0] lein0A;
  output [3:0] lein0B;
  wire [3:0] lein0B;
  output [3:0] lein1A;
  wire [3:0] lein1A;
  output [3:0] lein1B;
  wire [3:0] lein1B;
  input leout0A;
  wire leout0A;
  input leout0B;
  wire leout0B;
  input leout1A;
  wire leout1A;
  input leout1B;
  wire leout1B;
  input nrst;
  wire nrst;
  sky130_fd_sc_hd__mux4_2 _064_ (
    .A0(leout0A),
    .A1(leout0B),
    .A2(leout1A),
    .A3(leout1B),
    .S0(config_data[0]),
    .S1(config_data[1]),
    .X(_048_)
  );
  sky130_fd_sc_hd__nor2b_1 _065_ (
    .A(config_data[2]),
    .B_N(_048_),
    .Y(lein0A[0])
  );
  sky130_fd_sc_hd__mux4_2 _066_ (
    .A0(leout0A),
    .A1(leout0B),
    .A2(leout1A),
    .A3(leout1B),
    .S0(config_data[12]),
    .S1(config_data[13]),
    .X(_049_)
  );
  sky130_fd_sc_hd__nor2b_1 _067_ (
    .A(config_data[14]),
    .B_N(_049_),
    .Y(lein0A[1])
  );
  sky130_fd_sc_hd__mux4_2 _068_ (
    .A0(leout0A),
    .A1(leout0B),
    .A2(leout1A),
    .A3(leout1B),
    .S0(config_data[24]),
    .S1(config_data[25]),
    .X(_050_)
  );
  sky130_fd_sc_hd__nor2b_1 _069_ (
    .A(config_data[26]),
    .B_N(_050_),
    .Y(lein0A[2])
  );
  sky130_fd_sc_hd__mux4_2 _070_ (
    .A0(leout0A),
    .A1(leout0B),
    .A2(leout1A),
    .A3(leout1B),
    .S0(config_data[36]),
    .S1(config_data[37]),
    .X(_051_)
  );
  sky130_fd_sc_hd__nor2b_1 _071_ (
    .A(config_data[38]),
    .B_N(_051_),
    .Y(lein0A[3])
  );
  sky130_fd_sc_hd__mux4_2 _072_ (
    .A0(leout0A),
    .A1(leout0B),
    .A2(leout1A),
    .A3(leout1B),
    .S0(config_data[3]),
    .S1(config_data[4]),
    .X(_052_)
  );
  sky130_fd_sc_hd__nor2b_1 _073_ (
    .A(config_data[5]),
    .B_N(_052_),
    .Y(lein0B[0])
  );
  sky130_fd_sc_hd__mux4_2 _074_ (
    .A0(leout0A),
    .A1(leout0B),
    .A2(leout1A),
    .A3(leout1B),
    .S0(config_data[15]),
    .S1(config_data[16]),
    .X(_053_)
  );
  sky130_fd_sc_hd__nor2b_1 _075_ (
    .A(config_data[17]),
    .B_N(_053_),
    .Y(lein0B[1])
  );
  sky130_fd_sc_hd__mux4_2 _076_ (
    .A0(leout0A),
    .A1(leout0B),
    .A2(leout1A),
    .A3(leout1B),
    .S0(config_data[27]),
    .S1(config_data[28]),
    .X(_054_)
  );
  sky130_fd_sc_hd__nor2b_1 _077_ (
    .A(config_data[29]),
    .B_N(_054_),
    .Y(lein0B[2])
  );
  sky130_fd_sc_hd__mux4_2 _078_ (
    .A0(leout0A),
    .A1(leout0B),
    .A2(leout1A),
    .A3(leout1B),
    .S0(config_data[39]),
    .S1(config_data[40]),
    .X(_055_)
  );
  sky130_fd_sc_hd__nor2b_1 _079_ (
    .A(config_data[41]),
    .B_N(_055_),
    .Y(lein0B[3])
  );
  sky130_fd_sc_hd__mux4_2 _080_ (
    .A0(leout0A),
    .A1(leout0B),
    .A2(leout1A),
    .A3(leout1B),
    .S0(config_data[6]),
    .S1(config_data[7]),
    .X(_056_)
  );
  sky130_fd_sc_hd__nor2b_1 _081_ (
    .A(config_data[8]),
    .B_N(_056_),
    .Y(lein1A[0])
  );
  sky130_fd_sc_hd__mux4_2 _082_ (
    .A0(leout0A),
    .A1(leout0B),
    .A2(leout1A),
    .A3(leout1B),
    .S0(config_data[18]),
    .S1(config_data[19]),
    .X(_057_)
  );
  sky130_fd_sc_hd__nor2b_1 _083_ (
    .A(config_data[20]),
    .B_N(_057_),
    .Y(lein1A[1])
  );
  sky130_fd_sc_hd__mux4_2 _084_ (
    .A0(leout0A),
    .A1(leout0B),
    .A2(leout1A),
    .A3(leout1B),
    .S0(config_data[30]),
    .S1(config_data[31]),
    .X(_058_)
  );
  sky130_fd_sc_hd__nor2b_1 _085_ (
    .A(config_data[32]),
    .B_N(_058_),
    .Y(lein1A[2])
  );
  sky130_fd_sc_hd__mux4_2 _086_ (
    .A0(leout0A),
    .A1(leout0B),
    .A2(leout1A),
    .A3(leout1B),
    .S0(config_data[42]),
    .S1(config_data[43]),
    .X(_059_)
  );
  sky130_fd_sc_hd__nor2b_1 _087_ (
    .A(config_data[44]),
    .B_N(_059_),
    .Y(lein1A[3])
  );
  sky130_fd_sc_hd__mux4_2 _088_ (
    .A0(leout0A),
    .A1(leout0B),
    .A2(leout1A),
    .A3(leout1B),
    .S0(config_data[9]),
    .S1(config_data[10]),
    .X(_060_)
  );
  sky130_fd_sc_hd__nor2b_1 _089_ (
    .A(config_data[11]),
    .B_N(_060_),
    .Y(lein1B[0])
  );
  sky130_fd_sc_hd__mux4_2 _090_ (
    .A0(leout0A),
    .A1(leout0B),
    .A2(leout1A),
    .A3(leout1B),
    .S0(config_data[21]),
    .S1(config_data[22]),
    .X(_061_)
  );
  sky130_fd_sc_hd__nor2b_1 _091_ (
    .A(config_data[23]),
    .B_N(_061_),
    .Y(lein1B[1])
  );
  sky130_fd_sc_hd__mux4_2 _092_ (
    .A0(leout0A),
    .A1(leout0B),
    .A2(leout1A),
    .A3(leout1B),
    .S0(config_data[33]),
    .S1(config_data[34]),
    .X(_062_)
  );
  sky130_fd_sc_hd__nor2b_1 _093_ (
    .A(config_data[35]),
    .B_N(_062_),
    .Y(lein1B[2])
  );
  sky130_fd_sc_hd__mux4_2 _094_ (
    .A0(leout0A),
    .A1(leout0B),
    .A2(leout1A),
    .A3(leout1B),
    .S0(config_data[45]),
    .S1(config_data[46]),
    .X(_063_)
  );
  sky130_fd_sc_hd__nor2b_1 _095_ (
    .A(config_data[47]),
    .B_N(_063_),
    .Y(lein1B[3])
  );
  sky130_fd_sc_hd__mux2_1 _096_ (
    .A0(config_data[0]),
    .A1(config_data_in),
    .S(config_en),
    .X(_000_)
  );
  sky130_fd_sc_hd__mux2_1 _097_ (
    .A0(config_data[1]),
    .A1(config_data[0]),
    .S(config_en),
    .X(_001_)
  );
  sky130_fd_sc_hd__mux2_1 _098_ (
    .A0(config_data[2]),
    .A1(config_data[1]),
    .S(config_en),
    .X(_002_)
  );
  sky130_fd_sc_hd__mux2_1 _099_ (
    .A0(config_data[3]),
    .A1(config_data[2]),
    .S(config_en),
    .X(_003_)
  );
  sky130_fd_sc_hd__mux2_1 _100_ (
    .A0(config_data[4]),
    .A1(config_data[3]),
    .S(config_en),
    .X(_004_)
  );
  sky130_fd_sc_hd__mux2_1 _101_ (
    .A0(config_data[5]),
    .A1(config_data[4]),
    .S(config_en),
    .X(_005_)
  );
  sky130_fd_sc_hd__mux2_1 _102_ (
    .A0(config_data[6]),
    .A1(config_data[5]),
    .S(config_en),
    .X(_006_)
  );
  sky130_fd_sc_hd__mux2_1 _103_ (
    .A0(config_data[7]),
    .A1(config_data[6]),
    .S(config_en),
    .X(_007_)
  );
  sky130_fd_sc_hd__mux2_1 _104_ (
    .A0(config_data[8]),
    .A1(config_data[7]),
    .S(config_en),
    .X(_008_)
  );
  sky130_fd_sc_hd__mux2_1 _105_ (
    .A0(config_data[9]),
    .A1(config_data[8]),
    .S(config_en),
    .X(_009_)
  );
  sky130_fd_sc_hd__mux2_1 _106_ (
    .A0(config_data[10]),
    .A1(config_data[9]),
    .S(config_en),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux2_1 _107_ (
    .A0(config_data[11]),
    .A1(config_data[10]),
    .S(config_en),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _108_ (
    .A0(config_data[12]),
    .A1(config_data[11]),
    .S(config_en),
    .X(_012_)
  );
  sky130_fd_sc_hd__mux2_1 _109_ (
    .A0(config_data[13]),
    .A1(config_data[12]),
    .S(config_en),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _110_ (
    .A0(config_data[14]),
    .A1(config_data[13]),
    .S(config_en),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux2_1 _111_ (
    .A0(config_data[15]),
    .A1(config_data[14]),
    .S(config_en),
    .X(_015_)
  );
  sky130_fd_sc_hd__mux2_1 _112_ (
    .A0(config_data[16]),
    .A1(config_data[15]),
    .S(config_en),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _113_ (
    .A0(config_data[17]),
    .A1(config_data[16]),
    .S(config_en),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _114_ (
    .A0(config_data[18]),
    .A1(config_data[17]),
    .S(config_en),
    .X(_018_)
  );
  sky130_fd_sc_hd__mux2_1 _115_ (
    .A0(config_data[19]),
    .A1(config_data[18]),
    .S(config_en),
    .X(_019_)
  );
  sky130_fd_sc_hd__mux2_1 _116_ (
    .A0(config_data[20]),
    .A1(config_data[19]),
    .S(config_en),
    .X(_020_)
  );
  sky130_fd_sc_hd__mux2_1 _117_ (
    .A0(config_data[21]),
    .A1(config_data[20]),
    .S(config_en),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_1 _118_ (
    .A0(config_data[22]),
    .A1(config_data[21]),
    .S(config_en),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux2_1 _119_ (
    .A0(config_data[23]),
    .A1(config_data[22]),
    .S(config_en),
    .X(_023_)
  );
  sky130_fd_sc_hd__mux2_1 _120_ (
    .A0(config_data[24]),
    .A1(config_data[23]),
    .S(config_en),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2_1 _121_ (
    .A0(config_data[25]),
    .A1(config_data[24]),
    .S(config_en),
    .X(_025_)
  );
  sky130_fd_sc_hd__mux2_1 _122_ (
    .A0(config_data[26]),
    .A1(config_data[25]),
    .S(config_en),
    .X(_026_)
  );
  sky130_fd_sc_hd__mux2_1 _123_ (
    .A0(config_data[27]),
    .A1(config_data[26]),
    .S(config_en),
    .X(_027_)
  );
  sky130_fd_sc_hd__mux2_1 _124_ (
    .A0(config_data[28]),
    .A1(config_data[27]),
    .S(config_en),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2_1 _125_ (
    .A0(config_data[29]),
    .A1(config_data[28]),
    .S(config_en),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2_1 _126_ (
    .A0(config_data[30]),
    .A1(config_data[29]),
    .S(config_en),
    .X(_030_)
  );
  sky130_fd_sc_hd__mux2_1 _127_ (
    .A0(config_data[31]),
    .A1(config_data[30]),
    .S(config_en),
    .X(_031_)
  );
  sky130_fd_sc_hd__mux2_1 _128_ (
    .A0(config_data[32]),
    .A1(config_data[31]),
    .S(config_en),
    .X(_032_)
  );
  sky130_fd_sc_hd__mux2_1 _129_ (
    .A0(config_data[33]),
    .A1(config_data[32]),
    .S(config_en),
    .X(_033_)
  );
  sky130_fd_sc_hd__mux2_1 _130_ (
    .A0(config_data[34]),
    .A1(config_data[33]),
    .S(config_en),
    .X(_034_)
  );
  sky130_fd_sc_hd__mux2_1 _131_ (
    .A0(config_data[35]),
    .A1(config_data[34]),
    .S(config_en),
    .X(_035_)
  );
  sky130_fd_sc_hd__mux2_1 _132_ (
    .A0(config_data[36]),
    .A1(config_data[35]),
    .S(config_en),
    .X(_036_)
  );
  sky130_fd_sc_hd__mux2_1 _133_ (
    .A0(config_data[37]),
    .A1(config_data[36]),
    .S(config_en),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2_1 _134_ (
    .A0(config_data[38]),
    .A1(config_data[37]),
    .S(config_en),
    .X(_038_)
  );
  sky130_fd_sc_hd__mux2_1 _135_ (
    .A0(config_data[39]),
    .A1(config_data[38]),
    .S(config_en),
    .X(_039_)
  );
  sky130_fd_sc_hd__mux2_1 _136_ (
    .A0(config_data[40]),
    .A1(config_data[39]),
    .S(config_en),
    .X(_040_)
  );
  sky130_fd_sc_hd__mux2_1 _137_ (
    .A0(config_data[41]),
    .A1(config_data[40]),
    .S(config_en),
    .X(_041_)
  );
  sky130_fd_sc_hd__mux2_1 _138_ (
    .A0(config_data[42]),
    .A1(config_data[41]),
    .S(config_en),
    .X(_042_)
  );
  sky130_fd_sc_hd__mux2_1 _139_ (
    .A0(config_data[43]),
    .A1(config_data[42]),
    .S(config_en),
    .X(_043_)
  );
  sky130_fd_sc_hd__mux2_1 _140_ (
    .A0(config_data[44]),
    .A1(config_data[43]),
    .S(config_en),
    .X(_044_)
  );
  sky130_fd_sc_hd__mux2_1 _141_ (
    .A0(config_data[45]),
    .A1(config_data[44]),
    .S(config_en),
    .X(_045_)
  );
  sky130_fd_sc_hd__mux2_1 _142_ (
    .A0(config_data[46]),
    .A1(config_data[45]),
    .S(config_en),
    .X(_046_)
  );
  sky130_fd_sc_hd__mux2_1 _143_ (
    .A0(config_data[47]),
    .A1(config_data[46]),
    .S(config_en),
    .X(_047_)
  );
  sky130_fd_sc_hd__dfrtp_1 _144_ (
    .CLK(clk),
    .D(_000_),
    .Q(config_data[0]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _145_ (
    .CLK(clk),
    .D(_001_),
    .Q(config_data[1]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _146_ (
    .CLK(clk),
    .D(_002_),
    .Q(config_data[2]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _147_ (
    .CLK(clk),
    .D(_003_),
    .Q(config_data[3]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _148_ (
    .CLK(clk),
    .D(_004_),
    .Q(config_data[4]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _149_ (
    .CLK(clk),
    .D(_005_),
    .Q(config_data[5]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _150_ (
    .CLK(clk),
    .D(_006_),
    .Q(config_data[6]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _151_ (
    .CLK(clk),
    .D(_007_),
    .Q(config_data[7]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _152_ (
    .CLK(clk),
    .D(_008_),
    .Q(config_data[8]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _153_ (
    .CLK(clk),
    .D(_009_),
    .Q(config_data[9]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _154_ (
    .CLK(clk),
    .D(_010_),
    .Q(config_data[10]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _155_ (
    .CLK(clk),
    .D(_011_),
    .Q(config_data[11]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _156_ (
    .CLK(clk),
    .D(_012_),
    .Q(config_data[12]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _157_ (
    .CLK(clk),
    .D(_013_),
    .Q(config_data[13]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _158_ (
    .CLK(clk),
    .D(_014_),
    .Q(config_data[14]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _159_ (
    .CLK(clk),
    .D(_015_),
    .Q(config_data[15]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _160_ (
    .CLK(clk),
    .D(_016_),
    .Q(config_data[16]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _161_ (
    .CLK(clk),
    .D(_017_),
    .Q(config_data[17]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _162_ (
    .CLK(clk),
    .D(_018_),
    .Q(config_data[18]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _163_ (
    .CLK(clk),
    .D(_019_),
    .Q(config_data[19]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _164_ (
    .CLK(clk),
    .D(_020_),
    .Q(config_data[20]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _165_ (
    .CLK(clk),
    .D(_021_),
    .Q(config_data[21]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _166_ (
    .CLK(clk),
    .D(_022_),
    .Q(config_data[22]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _167_ (
    .CLK(clk),
    .D(_023_),
    .Q(config_data[23]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _168_ (
    .CLK(clk),
    .D(_024_),
    .Q(config_data[24]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _169_ (
    .CLK(clk),
    .D(_025_),
    .Q(config_data[25]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _170_ (
    .CLK(clk),
    .D(_026_),
    .Q(config_data[26]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _171_ (
    .CLK(clk),
    .D(_027_),
    .Q(config_data[27]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _172_ (
    .CLK(clk),
    .D(_028_),
    .Q(config_data[28]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _173_ (
    .CLK(clk),
    .D(_029_),
    .Q(config_data[29]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _174_ (
    .CLK(clk),
    .D(_030_),
    .Q(config_data[30]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _175_ (
    .CLK(clk),
    .D(_031_),
    .Q(config_data[31]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _176_ (
    .CLK(clk),
    .D(_032_),
    .Q(config_data[32]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _177_ (
    .CLK(clk),
    .D(_033_),
    .Q(config_data[33]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _178_ (
    .CLK(clk),
    .D(_034_),
    .Q(config_data[34]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _179_ (
    .CLK(clk),
    .D(_035_),
    .Q(config_data[35]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _180_ (
    .CLK(clk),
    .D(_036_),
    .Q(config_data[36]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _181_ (
    .CLK(clk),
    .D(_037_),
    .Q(config_data[37]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _182_ (
    .CLK(clk),
    .D(_038_),
    .Q(config_data[38]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _183_ (
    .CLK(clk),
    .D(_039_),
    .Q(config_data[39]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _184_ (
    .CLK(clk),
    .D(_040_),
    .Q(config_data[40]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _185_ (
    .CLK(clk),
    .D(_041_),
    .Q(config_data[41]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _186_ (
    .CLK(clk),
    .D(_042_),
    .Q(config_data[42]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _187_ (
    .CLK(clk),
    .D(_043_),
    .Q(config_data[43]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _188_ (
    .CLK(clk),
    .D(_044_),
    .Q(config_data[44]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _189_ (
    .CLK(clk),
    .D(_045_),
    .Q(config_data[45]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _190_ (
    .CLK(clk),
    .D(_046_),
    .Q(config_data[46]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _191_ (
    .CLK(clk),
    .D(_047_),
    .Q(config_data[47]),
    .RESET_B(nrst)
  );
  assign \concat_inputs[0]  = lein0A;
  assign \concat_inputs[1]  = lein0B;
  assign \concat_inputs[2]  = lein1A;
  assign \concat_inputs[3]  = lein1B;
  assign config_data_out = config_data[47];
  assign le_outputs = { leout1B, leout1A, leout0B, leout0A };
endmodule
