/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "source/wiltonSB.sv:3.1-76.10" *)
module wiltonSB(north, east, south, west, route_sel);
  (* src = "source/wiltonSB.sv:7.26-7.30" *)
  inout [7:0] east;
  wire [7:0] east;
  wire \east_$_TBUF__Y_1_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \east_$_TBUF__Y_1_E_SB_LUT4_O_I3 ;
  wire \east_$_TBUF__Y_2_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \east_$_TBUF__Y_2_E_SB_LUT4_O_I3 ;
  wire \east_$_TBUF__Y_3_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \east_$_TBUF__Y_3_E_SB_LUT4_O_I3 ;
  wire \east_$_TBUF__Y_4_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \east_$_TBUF__Y_4_E_SB_LUT4_O_I3 ;
  wire \east_$_TBUF__Y_5_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \east_$_TBUF__Y_5_E_SB_LUT4_O_I3 ;
  wire \east_$_TBUF__Y_6_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \east_$_TBUF__Y_6_E_SB_LUT4_O_I3 ;
  wire \east_$_TBUF__Y_7_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \east_$_TBUF__Y_7_E_SB_LUT4_O_I3 ;
  wire \east_$_TBUF__Y_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \east_$_TBUF__Y_E_SB_LUT4_O_I3 ;
  (* src = "source/wiltonSB.sv:6.26-6.31" *)
  inout [7:0] north;
  wire [7:0] north;
  wire \north_$_TBUF__Y_1_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \north_$_TBUF__Y_1_E_SB_LUT4_O_I3 ;
  wire \north_$_TBUF__Y_2_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \north_$_TBUF__Y_2_E_SB_LUT4_O_I3 ;
  wire \north_$_TBUF__Y_3_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \north_$_TBUF__Y_3_E_SB_LUT4_O_I3 ;
  wire \north_$_TBUF__Y_4_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \north_$_TBUF__Y_4_E_SB_LUT4_O_I3 ;
  wire \north_$_TBUF__Y_5_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \north_$_TBUF__Y_5_E_SB_LUT4_O_I3 ;
  wire \north_$_TBUF__Y_6_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \north_$_TBUF__Y_6_E_SB_LUT4_O_I3 ;
  wire \north_$_TBUF__Y_7_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \north_$_TBUF__Y_7_E_SB_LUT4_O_I3 ;
  wire \north_$_TBUF__Y_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \north_$_TBUF__Y_E_SB_LUT4_O_I3 ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:51$4866.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:51$4878.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:51$4890.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:51$4902.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:51$4914.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:51$4926.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:51$4938.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:51$4950.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:52$4867.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:52$4879.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:52$4891.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:52$4903.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:52$4915.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:52$4927.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:52$4939.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:52$4951.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:53$4868.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:53$4880.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:53$4892.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:53$4904.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:53$4916.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:53$4928.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:53$4940.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:53$4952.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:57$4869.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:57$4881.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:57$4893.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:57$4905.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:57$4917.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:57$4929.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:57$4941.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:57$4953.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:58$4870.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:58$4882.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:58$4894.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:58$4906.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:58$4918.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:58$4930.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:58$4942.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:58$4954.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:59$4871.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:59$4883.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:59$4895.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:59$4907.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:59$4919.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:59$4931.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:59$4943.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:59$4955.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:63$4872.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:63$4884.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:63$4896.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:63$4908.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:63$4920.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:63$4932.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:63$4944.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:63$4956.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:64$4873.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:64$4885.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:64$4897.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:64$4909.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:64$4921.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:64$4933.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:64$4945.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:64$4957.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:65$4874.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:65$4886.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:65$4898.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:65$4910.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:65$4922.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:65$4934.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:65$4946.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:65$4958.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:69$4875.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:69$4887.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:69$4899.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:69$4911.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:69$4923.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:69$4935.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:69$4947.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:69$4959.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:70$4876.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:70$4888.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:70$4900.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:70$4912.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:70$4924.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:70$4936.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:70$4948.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:70$4960.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:71$4877.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:71$4889.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:71$4901.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:71$4913.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:71$4925.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:71$4937.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:71$4949.turn ;
  (* nosync = 32'd1 *)
  (* src = "source/wiltonSB.sv:29.72-29.76" *)
  wire [1:0] \rot_dir$func$source/wiltonSB.sv:71$4961.turn ;
  (* src = "source/wiltonSB.sv:11.37-11.46" *)
  input [63:0] route_sel;
  wire [63:0] route_sel;
  (* src = "source/wiltonSB.sv:8.26-8.31" *)
  inout [7:0] south;
  wire [7:0] south;
  wire \south_$_TBUF__Y_1_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \south_$_TBUF__Y_1_E_SB_LUT4_O_I3 ;
  wire \south_$_TBUF__Y_2_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \south_$_TBUF__Y_2_E_SB_LUT4_O_I3 ;
  wire \south_$_TBUF__Y_3_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \south_$_TBUF__Y_3_E_SB_LUT4_O_I3 ;
  wire \south_$_TBUF__Y_4_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \south_$_TBUF__Y_4_E_SB_LUT4_O_I3 ;
  wire \south_$_TBUF__Y_5_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \south_$_TBUF__Y_5_E_SB_LUT4_O_I3 ;
  wire \south_$_TBUF__Y_6_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \south_$_TBUF__Y_6_E_SB_LUT4_O_I3 ;
  wire \south_$_TBUF__Y_7_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \south_$_TBUF__Y_7_E_SB_LUT4_O_I3 ;
  wire \south_$_TBUF__Y_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \south_$_TBUF__Y_E_SB_LUT4_O_I3 ;
  (* src = "source/wiltonSB.sv:9.26-9.30" *)
  inout [7:0] west;
  wire [7:0] west;
  wire \west_$_TBUF__Y_1_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \west_$_TBUF__Y_1_E_SB_LUT4_O_I3 ;
  wire \west_$_TBUF__Y_2_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \west_$_TBUF__Y_2_E_SB_LUT4_O_I3 ;
  wire \west_$_TBUF__Y_3_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \west_$_TBUF__Y_3_E_SB_LUT4_O_I3 ;
  wire \west_$_TBUF__Y_4_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \west_$_TBUF__Y_4_E_SB_LUT4_O_I3 ;
  wire \west_$_TBUF__Y_5_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \west_$_TBUF__Y_5_E_SB_LUT4_O_I3 ;
  wire \west_$_TBUF__Y_6_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \west_$_TBUF__Y_6_E_SB_LUT4_O_I3 ;
  wire \west_$_TBUF__Y_7_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \west_$_TBUF__Y_7_E_SB_LUT4_O_I3 ;
  wire \west_$_TBUF__Y_E ;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \west_$_TBUF__Y_E_SB_LUT4_O_I3 ;
  (* src = "source/wiltonSB.sv:21.20-21.28" *)
  wire [7:0] wire_bus;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] wire_bus_SB_LUT4_O_1_I0;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] wire_bus_SB_LUT4_O_1_I0_SB_LUT4_I3_O;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] wire_bus_SB_LUT4_O_2_I0;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] wire_bus_SB_LUT4_O_2_I0_SB_LUT4_I3_O;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] wire_bus_SB_LUT4_O_3_I0;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] wire_bus_SB_LUT4_O_3_I0_SB_LUT4_I3_O;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] wire_bus_SB_LUT4_O_4_I0;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] wire_bus_SB_LUT4_O_4_I0_SB_LUT4_I3_O;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] wire_bus_SB_LUT4_O_5_I0;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] wire_bus_SB_LUT4_O_5_I0_SB_LUT4_I3_O;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] wire_bus_SB_LUT4_O_6_I1;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [1:0] wire_bus_SB_LUT4_O_6_I1_SB_LUT4_O_2_I2;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] wire_bus_SB_LUT4_O_6_I1_SB_LUT4_O_2_I3;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] wire_bus_SB_LUT4_O_7_I0;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] wire_bus_SB_LUT4_O_7_I0_SB_LUT4_I3_O;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] wire_bus_SB_LUT4_O_I1;
  (* force_downto = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] wire_bus_SB_LUT4_O_I1_SB_LUT4_O_2_I2;
  (* src = "source/wiltonSB.sv:56.24-60.31" *)
  \$_TBUF_  \east_$_TBUF__Y  (
    .A(wire_bus[2]),
    .E(\east_$_TBUF__Y_E ),
    .Y(east[2])
  );
  (* src = "source/wiltonSB.sv:56.24-60.31" *)
  \$_TBUF_  \east_$_TBUF__Y_1  (
    .A(wire_bus[1]),
    .E(\east_$_TBUF__Y_1_E ),
    .Y(east[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h30ff)
  ) \east_$_TBUF__Y_1_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[15]),
    .I2(route_sel[14]),
    .I3(\east_$_TBUF__Y_1_E_SB_LUT4_O_I3 [2]),
    .O(\east_$_TBUF__Y_1_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hee0e)
  ) \east_$_TBUF__Y_1_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[13]),
    .I1(route_sel[12]),
    .I2(route_sel[9]),
    .I3(route_sel[8]),
    .O(\east_$_TBUF__Y_1_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:56.24-60.31" *)
  \$_TBUF_  \east_$_TBUF__Y_2  (
    .A(wire_bus[0]),
    .E(\east_$_TBUF__Y_2_E ),
    .Y(east[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h30ff)
  ) \east_$_TBUF__Y_2_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[7]),
    .I2(route_sel[6]),
    .I3(\east_$_TBUF__Y_2_E_SB_LUT4_O_I3 [2]),
    .O(\east_$_TBUF__Y_2_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hee0e)
  ) \east_$_TBUF__Y_2_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[5]),
    .I1(route_sel[4]),
    .I2(route_sel[1]),
    .I3(route_sel[0]),
    .O(\east_$_TBUF__Y_2_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:56.24-60.31" *)
  \$_TBUF_  \east_$_TBUF__Y_3  (
    .A(wire_bus[7]),
    .E(\east_$_TBUF__Y_3_E ),
    .Y(east[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h30ff)
  ) \east_$_TBUF__Y_3_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[63]),
    .I2(route_sel[62]),
    .I3(\east_$_TBUF__Y_3_E_SB_LUT4_O_I3 [2]),
    .O(\east_$_TBUF__Y_3_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hee0e)
  ) \east_$_TBUF__Y_3_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[61]),
    .I1(route_sel[60]),
    .I2(route_sel[57]),
    .I3(route_sel[56]),
    .O(\east_$_TBUF__Y_3_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:56.24-60.31" *)
  \$_TBUF_  \east_$_TBUF__Y_4  (
    .A(wire_bus[6]),
    .E(\east_$_TBUF__Y_4_E ),
    .Y(east[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h30ff)
  ) \east_$_TBUF__Y_4_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[55]),
    .I2(route_sel[54]),
    .I3(\east_$_TBUF__Y_4_E_SB_LUT4_O_I3 [2]),
    .O(\east_$_TBUF__Y_4_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hee0e)
  ) \east_$_TBUF__Y_4_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[53]),
    .I1(route_sel[52]),
    .I2(route_sel[49]),
    .I3(route_sel[48]),
    .O(\east_$_TBUF__Y_4_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:56.24-60.31" *)
  \$_TBUF_  \east_$_TBUF__Y_5  (
    .A(wire_bus[5]),
    .E(\east_$_TBUF__Y_5_E ),
    .Y(east[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h30ff)
  ) \east_$_TBUF__Y_5_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[47]),
    .I2(route_sel[46]),
    .I3(\east_$_TBUF__Y_5_E_SB_LUT4_O_I3 [2]),
    .O(\east_$_TBUF__Y_5_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hee0e)
  ) \east_$_TBUF__Y_5_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[45]),
    .I1(route_sel[44]),
    .I2(route_sel[41]),
    .I3(route_sel[40]),
    .O(\east_$_TBUF__Y_5_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:56.24-60.31" *)
  \$_TBUF_  \east_$_TBUF__Y_6  (
    .A(wire_bus[4]),
    .E(\east_$_TBUF__Y_6_E ),
    .Y(east[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h30ff)
  ) \east_$_TBUF__Y_6_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[39]),
    .I2(route_sel[38]),
    .I3(\east_$_TBUF__Y_6_E_SB_LUT4_O_I3 [2]),
    .O(\east_$_TBUF__Y_6_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hee0e)
  ) \east_$_TBUF__Y_6_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[37]),
    .I1(route_sel[36]),
    .I2(route_sel[33]),
    .I3(route_sel[32]),
    .O(\east_$_TBUF__Y_6_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:56.24-60.31" *)
  \$_TBUF_  \east_$_TBUF__Y_7  (
    .A(wire_bus[3]),
    .E(\east_$_TBUF__Y_7_E ),
    .Y(east[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h30ff)
  ) \east_$_TBUF__Y_7_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[31]),
    .I2(route_sel[30]),
    .I3(\east_$_TBUF__Y_7_E_SB_LUT4_O_I3 [2]),
    .O(\east_$_TBUF__Y_7_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hee0e)
  ) \east_$_TBUF__Y_7_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[29]),
    .I1(route_sel[28]),
    .I2(route_sel[25]),
    .I3(route_sel[24]),
    .O(\east_$_TBUF__Y_7_E_SB_LUT4_O_I3 [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h30ff)
  ) \east_$_TBUF__Y_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[23]),
    .I2(route_sel[22]),
    .I3(\east_$_TBUF__Y_E_SB_LUT4_O_I3 [2]),
    .O(\east_$_TBUF__Y_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hee0e)
  ) \east_$_TBUF__Y_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[21]),
    .I1(route_sel[20]),
    .I2(route_sel[17]),
    .I3(route_sel[16]),
    .O(\east_$_TBUF__Y_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:50.25-54.31" *)
  \$_TBUF_  \north_$_TBUF__Y  (
    .A(wire_bus[2]),
    .E(\north_$_TBUF__Y_E ),
    .Y(north[2])
  );
  (* src = "source/wiltonSB.sv:50.25-54.31" *)
  \$_TBUF_  \north_$_TBUF__Y_1  (
    .A(wire_bus[1]),
    .E(\north_$_TBUF__Y_1_E ),
    .Y(north[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0cff)
  ) \north_$_TBUF__Y_1_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[15]),
    .I2(route_sel[14]),
    .I3(\north_$_TBUF__Y_1_E_SB_LUT4_O_I3 [2]),
    .O(\north_$_TBUF__Y_1_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hbbb0)
  ) \north_$_TBUF__Y_1_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[13]),
    .I1(route_sel[12]),
    .I2(route_sel[11]),
    .I3(route_sel[10]),
    .O(\north_$_TBUF__Y_1_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:50.25-54.31" *)
  \$_TBUF_  \north_$_TBUF__Y_2  (
    .A(wire_bus[0]),
    .E(\north_$_TBUF__Y_2_E ),
    .Y(north[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0cff)
  ) \north_$_TBUF__Y_2_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[7]),
    .I2(route_sel[6]),
    .I3(\north_$_TBUF__Y_2_E_SB_LUT4_O_I3 [2]),
    .O(\north_$_TBUF__Y_2_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hbbb0)
  ) \north_$_TBUF__Y_2_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[5]),
    .I1(route_sel[4]),
    .I2(route_sel[3]),
    .I3(route_sel[2]),
    .O(\north_$_TBUF__Y_2_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:50.25-54.31" *)
  \$_TBUF_  \north_$_TBUF__Y_3  (
    .A(wire_bus[7]),
    .E(\north_$_TBUF__Y_3_E ),
    .Y(north[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0cff)
  ) \north_$_TBUF__Y_3_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[63]),
    .I2(route_sel[62]),
    .I3(\north_$_TBUF__Y_3_E_SB_LUT4_O_I3 [2]),
    .O(\north_$_TBUF__Y_3_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hbbb0)
  ) \north_$_TBUF__Y_3_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[61]),
    .I1(route_sel[60]),
    .I2(route_sel[59]),
    .I3(route_sel[58]),
    .O(\north_$_TBUF__Y_3_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:50.25-54.31" *)
  \$_TBUF_  \north_$_TBUF__Y_4  (
    .A(wire_bus[6]),
    .E(\north_$_TBUF__Y_4_E ),
    .Y(north[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0cff)
  ) \north_$_TBUF__Y_4_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[55]),
    .I2(route_sel[54]),
    .I3(\north_$_TBUF__Y_4_E_SB_LUT4_O_I3 [2]),
    .O(\north_$_TBUF__Y_4_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hbbb0)
  ) \north_$_TBUF__Y_4_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[53]),
    .I1(route_sel[52]),
    .I2(route_sel[51]),
    .I3(route_sel[50]),
    .O(\north_$_TBUF__Y_4_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:50.25-54.31" *)
  \$_TBUF_  \north_$_TBUF__Y_5  (
    .A(wire_bus[5]),
    .E(\north_$_TBUF__Y_5_E ),
    .Y(north[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0cff)
  ) \north_$_TBUF__Y_5_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[47]),
    .I2(route_sel[46]),
    .I3(\north_$_TBUF__Y_5_E_SB_LUT4_O_I3 [2]),
    .O(\north_$_TBUF__Y_5_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hbbb0)
  ) \north_$_TBUF__Y_5_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[45]),
    .I1(route_sel[44]),
    .I2(route_sel[43]),
    .I3(route_sel[42]),
    .O(\north_$_TBUF__Y_5_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:50.25-54.31" *)
  \$_TBUF_  \north_$_TBUF__Y_6  (
    .A(wire_bus[4]),
    .E(\north_$_TBUF__Y_6_E ),
    .Y(north[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0cff)
  ) \north_$_TBUF__Y_6_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[39]),
    .I2(route_sel[38]),
    .I3(\north_$_TBUF__Y_6_E_SB_LUT4_O_I3 [2]),
    .O(\north_$_TBUF__Y_6_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hbbb0)
  ) \north_$_TBUF__Y_6_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[37]),
    .I1(route_sel[36]),
    .I2(route_sel[35]),
    .I3(route_sel[34]),
    .O(\north_$_TBUF__Y_6_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:50.25-54.31" *)
  \$_TBUF_  \north_$_TBUF__Y_7  (
    .A(wire_bus[3]),
    .E(\north_$_TBUF__Y_7_E ),
    .Y(north[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0cff)
  ) \north_$_TBUF__Y_7_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[31]),
    .I2(route_sel[30]),
    .I3(\north_$_TBUF__Y_7_E_SB_LUT4_O_I3 [2]),
    .O(\north_$_TBUF__Y_7_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hbbb0)
  ) \north_$_TBUF__Y_7_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[29]),
    .I1(route_sel[28]),
    .I2(route_sel[27]),
    .I3(route_sel[26]),
    .O(\north_$_TBUF__Y_7_E_SB_LUT4_O_I3 [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0cff)
  ) \north_$_TBUF__Y_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[23]),
    .I2(route_sel[22]),
    .I3(\north_$_TBUF__Y_E_SB_LUT4_O_I3 [2]),
    .O(\north_$_TBUF__Y_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hbbb0)
  ) \north_$_TBUF__Y_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[21]),
    .I1(route_sel[20]),
    .I2(route_sel[19]),
    .I3(route_sel[18]),
    .O(\north_$_TBUF__Y_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:62.25-66.31" *)
  \$_TBUF_  \south_$_TBUF__Y  (
    .A(wire_bus[2]),
    .E(\south_$_TBUF__Y_E ),
    .Y(south[2])
  );
  (* src = "source/wiltonSB.sv:62.25-66.31" *)
  \$_TBUF_  \south_$_TBUF__Y_1  (
    .A(wire_bus[1]),
    .E(\south_$_TBUF__Y_1_E ),
    .Y(south[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h03ff)
  ) \south_$_TBUF__Y_1_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[15]),
    .I2(route_sel[14]),
    .I3(\south_$_TBUF__Y_1_E_SB_LUT4_O_I3 [2]),
    .O(\south_$_TBUF__Y_1_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hd0dd)
  ) \south_$_TBUF__Y_1_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[11]),
    .I1(route_sel[10]),
    .I2(route_sel[9]),
    .I3(route_sel[8]),
    .O(\south_$_TBUF__Y_1_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:62.25-66.31" *)
  \$_TBUF_  \south_$_TBUF__Y_2  (
    .A(wire_bus[0]),
    .E(\south_$_TBUF__Y_2_E ),
    .Y(south[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h03ff)
  ) \south_$_TBUF__Y_2_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[7]),
    .I2(route_sel[6]),
    .I3(\south_$_TBUF__Y_2_E_SB_LUT4_O_I3 [2]),
    .O(\south_$_TBUF__Y_2_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hd0dd)
  ) \south_$_TBUF__Y_2_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[3]),
    .I1(route_sel[2]),
    .I2(route_sel[1]),
    .I3(route_sel[0]),
    .O(\south_$_TBUF__Y_2_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:62.25-66.31" *)
  \$_TBUF_  \south_$_TBUF__Y_3  (
    .A(wire_bus[7]),
    .E(\south_$_TBUF__Y_3_E ),
    .Y(south[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h03ff)
  ) \south_$_TBUF__Y_3_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[63]),
    .I2(route_sel[62]),
    .I3(\south_$_TBUF__Y_3_E_SB_LUT4_O_I3 [2]),
    .O(\south_$_TBUF__Y_3_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hd0dd)
  ) \south_$_TBUF__Y_3_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[59]),
    .I1(route_sel[58]),
    .I2(route_sel[57]),
    .I3(route_sel[56]),
    .O(\south_$_TBUF__Y_3_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:62.25-66.31" *)
  \$_TBUF_  \south_$_TBUF__Y_4  (
    .A(wire_bus[6]),
    .E(\south_$_TBUF__Y_4_E ),
    .Y(south[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h03ff)
  ) \south_$_TBUF__Y_4_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[55]),
    .I2(route_sel[54]),
    .I3(\south_$_TBUF__Y_4_E_SB_LUT4_O_I3 [2]),
    .O(\south_$_TBUF__Y_4_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hd0dd)
  ) \south_$_TBUF__Y_4_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[51]),
    .I1(route_sel[50]),
    .I2(route_sel[49]),
    .I3(route_sel[48]),
    .O(\south_$_TBUF__Y_4_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:62.25-66.31" *)
  \$_TBUF_  \south_$_TBUF__Y_5  (
    .A(wire_bus[5]),
    .E(\south_$_TBUF__Y_5_E ),
    .Y(south[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h03ff)
  ) \south_$_TBUF__Y_5_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[47]),
    .I2(route_sel[46]),
    .I3(\south_$_TBUF__Y_5_E_SB_LUT4_O_I3 [2]),
    .O(\south_$_TBUF__Y_5_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hd0dd)
  ) \south_$_TBUF__Y_5_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[43]),
    .I1(route_sel[42]),
    .I2(route_sel[41]),
    .I3(route_sel[40]),
    .O(\south_$_TBUF__Y_5_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:62.25-66.31" *)
  \$_TBUF_  \south_$_TBUF__Y_6  (
    .A(wire_bus[4]),
    .E(\south_$_TBUF__Y_6_E ),
    .Y(south[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h03ff)
  ) \south_$_TBUF__Y_6_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[39]),
    .I2(route_sel[38]),
    .I3(\south_$_TBUF__Y_6_E_SB_LUT4_O_I3 [2]),
    .O(\south_$_TBUF__Y_6_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hd0dd)
  ) \south_$_TBUF__Y_6_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[35]),
    .I1(route_sel[34]),
    .I2(route_sel[33]),
    .I3(route_sel[32]),
    .O(\south_$_TBUF__Y_6_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:62.25-66.31" *)
  \$_TBUF_  \south_$_TBUF__Y_7  (
    .A(wire_bus[3]),
    .E(\south_$_TBUF__Y_7_E ),
    .Y(south[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h03ff)
  ) \south_$_TBUF__Y_7_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[31]),
    .I2(route_sel[30]),
    .I3(\south_$_TBUF__Y_7_E_SB_LUT4_O_I3 [2]),
    .O(\south_$_TBUF__Y_7_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hd0dd)
  ) \south_$_TBUF__Y_7_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[27]),
    .I1(route_sel[26]),
    .I2(route_sel[25]),
    .I3(route_sel[24]),
    .O(\south_$_TBUF__Y_7_E_SB_LUT4_O_I3 [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h03ff)
  ) \south_$_TBUF__Y_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[23]),
    .I2(route_sel[22]),
    .I3(\south_$_TBUF__Y_E_SB_LUT4_O_I3 [2]),
    .O(\south_$_TBUF__Y_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hd0dd)
  ) \south_$_TBUF__Y_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[19]),
    .I1(route_sel[18]),
    .I2(route_sel[17]),
    .I3(route_sel[16]),
    .O(\south_$_TBUF__Y_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:68.24-72.31" *)
  \$_TBUF_  \west_$_TBUF__Y  (
    .A(wire_bus[1]),
    .E(\west_$_TBUF__Y_E ),
    .Y(west[1])
  );
  (* src = "source/wiltonSB.sv:68.24-72.31" *)
  \$_TBUF_  \west_$_TBUF__Y_1  (
    .A(wire_bus[0]),
    .E(\west_$_TBUF__Y_1_E ),
    .Y(west[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0cff)
  ) \west_$_TBUF__Y_1_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[5]),
    .I2(route_sel[4]),
    .I3(\west_$_TBUF__Y_1_E_SB_LUT4_O_I3 [2]),
    .O(\west_$_TBUF__Y_1_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hbbb0)
  ) \west_$_TBUF__Y_1_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[3]),
    .I1(route_sel[2]),
    .I2(route_sel[1]),
    .I3(route_sel[0]),
    .O(\west_$_TBUF__Y_1_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:68.24-72.31" *)
  \$_TBUF_  \west_$_TBUF__Y_2  (
    .A(wire_bus[7]),
    .E(\west_$_TBUF__Y_2_E ),
    .Y(west[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0cff)
  ) \west_$_TBUF__Y_2_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[61]),
    .I2(route_sel[60]),
    .I3(\west_$_TBUF__Y_2_E_SB_LUT4_O_I3 [2]),
    .O(\west_$_TBUF__Y_2_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hbbb0)
  ) \west_$_TBUF__Y_2_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[59]),
    .I1(route_sel[58]),
    .I2(route_sel[57]),
    .I3(route_sel[56]),
    .O(\west_$_TBUF__Y_2_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:68.24-72.31" *)
  \$_TBUF_  \west_$_TBUF__Y_3  (
    .A(wire_bus[6]),
    .E(\west_$_TBUF__Y_3_E ),
    .Y(west[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0cff)
  ) \west_$_TBUF__Y_3_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[53]),
    .I2(route_sel[52]),
    .I3(\west_$_TBUF__Y_3_E_SB_LUT4_O_I3 [2]),
    .O(\west_$_TBUF__Y_3_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hbbb0)
  ) \west_$_TBUF__Y_3_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[51]),
    .I1(route_sel[50]),
    .I2(route_sel[49]),
    .I3(route_sel[48]),
    .O(\west_$_TBUF__Y_3_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:68.24-72.31" *)
  \$_TBUF_  \west_$_TBUF__Y_4  (
    .A(wire_bus[5]),
    .E(\west_$_TBUF__Y_4_E ),
    .Y(west[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0cff)
  ) \west_$_TBUF__Y_4_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[45]),
    .I2(route_sel[44]),
    .I3(\west_$_TBUF__Y_4_E_SB_LUT4_O_I3 [2]),
    .O(\west_$_TBUF__Y_4_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hbbb0)
  ) \west_$_TBUF__Y_4_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[43]),
    .I1(route_sel[42]),
    .I2(route_sel[41]),
    .I3(route_sel[40]),
    .O(\west_$_TBUF__Y_4_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:68.24-72.31" *)
  \$_TBUF_  \west_$_TBUF__Y_5  (
    .A(wire_bus[4]),
    .E(\west_$_TBUF__Y_5_E ),
    .Y(west[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0cff)
  ) \west_$_TBUF__Y_5_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[37]),
    .I2(route_sel[36]),
    .I3(\west_$_TBUF__Y_5_E_SB_LUT4_O_I3 [2]),
    .O(\west_$_TBUF__Y_5_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hbbb0)
  ) \west_$_TBUF__Y_5_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[35]),
    .I1(route_sel[34]),
    .I2(route_sel[33]),
    .I3(route_sel[32]),
    .O(\west_$_TBUF__Y_5_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:68.24-72.31" *)
  \$_TBUF_  \west_$_TBUF__Y_6  (
    .A(wire_bus[3]),
    .E(\west_$_TBUF__Y_6_E ),
    .Y(west[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0cff)
  ) \west_$_TBUF__Y_6_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[29]),
    .I2(route_sel[28]),
    .I3(\west_$_TBUF__Y_6_E_SB_LUT4_O_I3 [2]),
    .O(\west_$_TBUF__Y_6_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hbbb0)
  ) \west_$_TBUF__Y_6_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[27]),
    .I1(route_sel[26]),
    .I2(route_sel[25]),
    .I3(route_sel[24]),
    .O(\west_$_TBUF__Y_6_E_SB_LUT4_O_I3 [2])
  );
  (* src = "source/wiltonSB.sv:68.24-72.31" *)
  \$_TBUF_  \west_$_TBUF__Y_7  (
    .A(wire_bus[2]),
    .E(\west_$_TBUF__Y_7_E ),
    .Y(west[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0cff)
  ) \west_$_TBUF__Y_7_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[21]),
    .I2(route_sel[20]),
    .I3(\west_$_TBUF__Y_7_E_SB_LUT4_O_I3 [2]),
    .O(\west_$_TBUF__Y_7_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hbbb0)
  ) \west_$_TBUF__Y_7_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[19]),
    .I1(route_sel[18]),
    .I2(route_sel[17]),
    .I3(route_sel[16]),
    .O(\west_$_TBUF__Y_7_E_SB_LUT4_O_I3 [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0cff)
  ) \west_$_TBUF__Y_E_SB_LUT4_O  (
    .I0(1'h0),
    .I1(route_sel[13]),
    .I2(route_sel[12]),
    .I3(\west_$_TBUF__Y_E_SB_LUT4_O_I3 [2]),
    .O(\west_$_TBUF__Y_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hbbb0)
  ) \west_$_TBUF__Y_E_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(route_sel[11]),
    .I1(route_sel[10]),
    .I2(route_sel[9]),
    .I3(route_sel[8]),
    .O(\west_$_TBUF__Y_E_SB_LUT4_O_I3 [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'heee2)
  ) wire_bus_SB_LUT4_O (
    .I0(north[7]),
    .I1(wire_bus_SB_LUT4_O_I1[1]),
    .I2(wire_bus_SB_LUT4_O_I1[2]),
    .I3(wire_bus_SB_LUT4_O_I1[3]),
    .O(wire_bus[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h2033)
  ) wire_bus_SB_LUT4_O_1 (
    .I0(wire_bus_SB_LUT4_O_1_I0[3]),
    .I1(wire_bus_SB_LUT4_O_1_I0_SB_LUT4_I3_O[1]),
    .I2(wire_bus_SB_LUT4_O_1_I0_SB_LUT4_I3_O[2]),
    .I3(wire_bus_SB_LUT4_O_1_I0_SB_LUT4_I3_O[3]),
    .O(wire_bus[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8808)
  ) wire_bus_SB_LUT4_O_1_I0_SB_LUT4_I3 (
    .I0(route_sel[49]),
    .I1(route_sel[48]),
    .I2(east[6]),
    .I3(wire_bus_SB_LUT4_O_1_I0[3]),
    .O(wire_bus_SB_LUT4_O_1_I0_SB_LUT4_I3_O[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h003f)
  ) wire_bus_SB_LUT4_O_1_I0_SB_LUT4_I3_O_SB_LUT4_O (
    .I0(1'h0),
    .I1(route_sel[49]),
    .I2(route_sel[48]),
    .I3(north[6]),
    .O(wire_bus_SB_LUT4_O_1_I0_SB_LUT4_I3_O[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf780)
  ) wire_bus_SB_LUT4_O_1_I0_SB_LUT4_I3_O_SB_LUT4_O_1 (
    .I0(route_sel[53]),
    .I1(route_sel[52]),
    .I2(west[6]),
    .I3(south[6]),
    .O(wire_bus_SB_LUT4_O_1_I0_SB_LUT4_I3_O[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) wire_bus_SB_LUT4_O_1_I0_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(route_sel[51]),
    .I3(route_sel[50]),
    .O(wire_bus_SB_LUT4_O_1_I0[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h2033)
  ) wire_bus_SB_LUT4_O_2 (
    .I0(wire_bus_SB_LUT4_O_2_I0[3]),
    .I1(wire_bus_SB_LUT4_O_2_I0_SB_LUT4_I3_O[1]),
    .I2(wire_bus_SB_LUT4_O_2_I0_SB_LUT4_I3_O[2]),
    .I3(wire_bus_SB_LUT4_O_2_I0_SB_LUT4_I3_O[3]),
    .O(wire_bus[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8808)
  ) wire_bus_SB_LUT4_O_2_I0_SB_LUT4_I3 (
    .I0(route_sel[41]),
    .I1(route_sel[40]),
    .I2(east[5]),
    .I3(wire_bus_SB_LUT4_O_2_I0[3]),
    .O(wire_bus_SB_LUT4_O_2_I0_SB_LUT4_I3_O[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h003f)
  ) wire_bus_SB_LUT4_O_2_I0_SB_LUT4_I3_O_SB_LUT4_O (
    .I0(1'h0),
    .I1(route_sel[41]),
    .I2(route_sel[40]),
    .I3(north[5]),
    .O(wire_bus_SB_LUT4_O_2_I0_SB_LUT4_I3_O[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf780)
  ) wire_bus_SB_LUT4_O_2_I0_SB_LUT4_I3_O_SB_LUT4_O_1 (
    .I0(route_sel[45]),
    .I1(route_sel[44]),
    .I2(west[5]),
    .I3(south[5]),
    .O(wire_bus_SB_LUT4_O_2_I0_SB_LUT4_I3_O[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) wire_bus_SB_LUT4_O_2_I0_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(route_sel[43]),
    .I3(route_sel[42]),
    .O(wire_bus_SB_LUT4_O_2_I0[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h2033)
  ) wire_bus_SB_LUT4_O_3 (
    .I0(wire_bus_SB_LUT4_O_3_I0[3]),
    .I1(wire_bus_SB_LUT4_O_3_I0_SB_LUT4_I3_O[1]),
    .I2(wire_bus_SB_LUT4_O_3_I0_SB_LUT4_I3_O[2]),
    .I3(wire_bus_SB_LUT4_O_3_I0_SB_LUT4_I3_O[3]),
    .O(wire_bus[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8808)
  ) wire_bus_SB_LUT4_O_3_I0_SB_LUT4_I3 (
    .I0(route_sel[33]),
    .I1(route_sel[32]),
    .I2(east[4]),
    .I3(wire_bus_SB_LUT4_O_3_I0[3]),
    .O(wire_bus_SB_LUT4_O_3_I0_SB_LUT4_I3_O[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h003f)
  ) wire_bus_SB_LUT4_O_3_I0_SB_LUT4_I3_O_SB_LUT4_O (
    .I0(1'h0),
    .I1(route_sel[33]),
    .I2(route_sel[32]),
    .I3(north[4]),
    .O(wire_bus_SB_LUT4_O_3_I0_SB_LUT4_I3_O[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf780)
  ) wire_bus_SB_LUT4_O_3_I0_SB_LUT4_I3_O_SB_LUT4_O_1 (
    .I0(route_sel[37]),
    .I1(route_sel[36]),
    .I2(west[4]),
    .I3(south[4]),
    .O(wire_bus_SB_LUT4_O_3_I0_SB_LUT4_I3_O[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) wire_bus_SB_LUT4_O_3_I0_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(route_sel[35]),
    .I3(route_sel[34]),
    .O(wire_bus_SB_LUT4_O_3_I0[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h2033)
  ) wire_bus_SB_LUT4_O_4 (
    .I0(wire_bus_SB_LUT4_O_4_I0[3]),
    .I1(wire_bus_SB_LUT4_O_4_I0_SB_LUT4_I3_O[1]),
    .I2(wire_bus_SB_LUT4_O_4_I0_SB_LUT4_I3_O[2]),
    .I3(wire_bus_SB_LUT4_O_4_I0_SB_LUT4_I3_O[3]),
    .O(wire_bus[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8808)
  ) wire_bus_SB_LUT4_O_4_I0_SB_LUT4_I3 (
    .I0(route_sel[25]),
    .I1(route_sel[24]),
    .I2(east[3]),
    .I3(wire_bus_SB_LUT4_O_4_I0[3]),
    .O(wire_bus_SB_LUT4_O_4_I0_SB_LUT4_I3_O[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h003f)
  ) wire_bus_SB_LUT4_O_4_I0_SB_LUT4_I3_O_SB_LUT4_O (
    .I0(1'h0),
    .I1(route_sel[25]),
    .I2(route_sel[24]),
    .I3(north[3]),
    .O(wire_bus_SB_LUT4_O_4_I0_SB_LUT4_I3_O[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf780)
  ) wire_bus_SB_LUT4_O_4_I0_SB_LUT4_I3_O_SB_LUT4_O_1 (
    .I0(route_sel[29]),
    .I1(route_sel[28]),
    .I2(west[3]),
    .I3(south[3]),
    .O(wire_bus_SB_LUT4_O_4_I0_SB_LUT4_I3_O[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) wire_bus_SB_LUT4_O_4_I0_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(route_sel[27]),
    .I3(route_sel[26]),
    .O(wire_bus_SB_LUT4_O_4_I0[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h2033)
  ) wire_bus_SB_LUT4_O_5 (
    .I0(wire_bus_SB_LUT4_O_5_I0[3]),
    .I1(wire_bus_SB_LUT4_O_5_I0_SB_LUT4_I3_O[1]),
    .I2(wire_bus_SB_LUT4_O_5_I0_SB_LUT4_I3_O[2]),
    .I3(wire_bus_SB_LUT4_O_5_I0_SB_LUT4_I3_O[3]),
    .O(wire_bus[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8808)
  ) wire_bus_SB_LUT4_O_5_I0_SB_LUT4_I3 (
    .I0(route_sel[17]),
    .I1(route_sel[16]),
    .I2(east[2]),
    .I3(wire_bus_SB_LUT4_O_5_I0[3]),
    .O(wire_bus_SB_LUT4_O_5_I0_SB_LUT4_I3_O[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h003f)
  ) wire_bus_SB_LUT4_O_5_I0_SB_LUT4_I3_O_SB_LUT4_O (
    .I0(1'h0),
    .I1(route_sel[17]),
    .I2(route_sel[16]),
    .I3(north[2]),
    .O(wire_bus_SB_LUT4_O_5_I0_SB_LUT4_I3_O[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf780)
  ) wire_bus_SB_LUT4_O_5_I0_SB_LUT4_I3_O_SB_LUT4_O_1 (
    .I0(route_sel[21]),
    .I1(route_sel[20]),
    .I2(west[2]),
    .I3(south[2]),
    .O(wire_bus_SB_LUT4_O_5_I0_SB_LUT4_I3_O[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) wire_bus_SB_LUT4_O_5_I0_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(route_sel[19]),
    .I3(route_sel[18]),
    .O(wire_bus_SB_LUT4_O_5_I0[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'heee2)
  ) wire_bus_SB_LUT4_O_6 (
    .I0(north[1]),
    .I1(wire_bus_SB_LUT4_O_6_I1[1]),
    .I2(wire_bus_SB_LUT4_O_6_I1[2]),
    .I3(wire_bus_SB_LUT4_O_6_I1[3]),
    .O(wire_bus[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) wire_bus_SB_LUT4_O_6_I1_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(route_sel[9]),
    .I3(route_sel[8]),
    .O(wire_bus_SB_LUT4_O_6_I1[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h00f0)
  ) wire_bus_SB_LUT4_O_6_I1_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(east[1]),
    .I3(wire_bus_SB_LUT4_O_6_I1_SB_LUT4_O_2_I2[1]),
    .O(wire_bus_SB_LUT4_O_6_I1[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'ha0c0)
  ) wire_bus_SB_LUT4_O_6_I1_SB_LUT4_O_2 (
    .I0(west[1]),
    .I1(south[1]),
    .I2(wire_bus_SB_LUT4_O_6_I1_SB_LUT4_O_2_I2[1]),
    .I3(wire_bus_SB_LUT4_O_6_I1_SB_LUT4_O_2_I3[3]),
    .O(wire_bus_SB_LUT4_O_6_I1[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) wire_bus_SB_LUT4_O_6_I1_SB_LUT4_O_2_I2_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(route_sel[11]),
    .I3(route_sel[10]),
    .O(wire_bus_SB_LUT4_O_6_I1_SB_LUT4_O_2_I2[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) wire_bus_SB_LUT4_O_6_I1_SB_LUT4_O_2_I3_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(route_sel[13]),
    .I3(route_sel[12]),
    .O(wire_bus_SB_LUT4_O_6_I1_SB_LUT4_O_2_I3[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h2033)
  ) wire_bus_SB_LUT4_O_7 (
    .I0(wire_bus_SB_LUT4_O_7_I0[3]),
    .I1(wire_bus_SB_LUT4_O_7_I0_SB_LUT4_I3_O[1]),
    .I2(wire_bus_SB_LUT4_O_7_I0_SB_LUT4_I3_O[2]),
    .I3(wire_bus_SB_LUT4_O_7_I0_SB_LUT4_I3_O[3]),
    .O(wire_bus[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8808)
  ) wire_bus_SB_LUT4_O_7_I0_SB_LUT4_I3 (
    .I0(route_sel[1]),
    .I1(route_sel[0]),
    .I2(east[0]),
    .I3(wire_bus_SB_LUT4_O_7_I0[3]),
    .O(wire_bus_SB_LUT4_O_7_I0_SB_LUT4_I3_O[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h003f)
  ) wire_bus_SB_LUT4_O_7_I0_SB_LUT4_I3_O_SB_LUT4_O (
    .I0(1'h0),
    .I1(route_sel[1]),
    .I2(route_sel[0]),
    .I3(north[0]),
    .O(wire_bus_SB_LUT4_O_7_I0_SB_LUT4_I3_O[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf780)
  ) wire_bus_SB_LUT4_O_7_I0_SB_LUT4_I3_O_SB_LUT4_O_1 (
    .I0(route_sel[5]),
    .I1(route_sel[4]),
    .I2(west[0]),
    .I3(south[0]),
    .O(wire_bus_SB_LUT4_O_7_I0_SB_LUT4_I3_O[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) wire_bus_SB_LUT4_O_7_I0_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(route_sel[3]),
    .I3(route_sel[2]),
    .O(wire_bus_SB_LUT4_O_7_I0[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) wire_bus_SB_LUT4_O_I1_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(route_sel[57]),
    .I3(route_sel[56]),
    .O(wire_bus_SB_LUT4_O_I1[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h00f0)
  ) wire_bus_SB_LUT4_O_I1_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(east[7]),
    .I3(wire_bus_SB_LUT4_O_I1_SB_LUT4_O_2_I2[2]),
    .O(wire_bus_SB_LUT4_O_I1[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'ha0c0)
  ) wire_bus_SB_LUT4_O_I1_SB_LUT4_O_2 (
    .I0(west[7]),
    .I1(south[7]),
    .I2(wire_bus_SB_LUT4_O_I1_SB_LUT4_O_2_I2[2]),
    .I3(wire_bus_SB_LUT4_O_I1_SB_LUT4_O_2_I2[3]),
    .O(wire_bus_SB_LUT4_O_I1[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) wire_bus_SB_LUT4_O_I1_SB_LUT4_O_2_I2_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(route_sel[59]),
    .I3(route_sel[58]),
    .O(wire_bus_SB_LUT4_O_I1_SB_LUT4_O_2_I2[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/shay/a/ece270/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) wire_bus_SB_LUT4_O_I1_SB_LUT4_O_2_I2_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(route_sel[61]),
    .I3(route_sel[60]),
    .O(wire_bus_SB_LUT4_O_I1_SB_LUT4_O_2_I2[3])
  );
  assign wire_bus_SB_LUT4_O_I1_SB_LUT4_O_2_I2[1:0] = { south[7], west[7] };
  assign \south_$_TBUF__Y_5_E_SB_LUT4_O_I3 [1:0] = { route_sel[46], route_sel[47] };
  assign \west_$_TBUF__Y_4_E_SB_LUT4_O_I3 [1:0] = { route_sel[44], route_sel[45] };
  assign \west_$_TBUF__Y_5_E_SB_LUT4_O_I3 [1:0] = { route_sel[36], route_sel[37] };
  assign \north_$_TBUF__Y_6_E_SB_LUT4_O_I3 [1:0] = { route_sel[38], route_sel[39] };
  assign wire_bus_SB_LUT4_O_7_I0[2:0] = { east[0], route_sel[0], route_sel[1] };
  assign \north_$_TBUF__Y_4_E_SB_LUT4_O_I3 [1:0] = { route_sel[54], route_sel[55] };
  assign \east_$_TBUF__Y_5_E_SB_LUT4_O_I3 [1:0] = { route_sel[46], route_sel[47] };
  assign \north_$_TBUF__Y_5_E_SB_LUT4_O_I3 [1:0] = { route_sel[46], route_sel[47] };
  assign \south_$_TBUF__Y_6_E_SB_LUT4_O_I3 [1:0] = { route_sel[38], route_sel[39] };
  assign \south_$_TBUF__Y_3_E_SB_LUT4_O_I3 [1:0] = { route_sel[62], route_sel[63] };
  assign \south_$_TBUF__Y_1_E_SB_LUT4_O_I3 [1:0] = { route_sel[14], route_sel[15] };
  assign \east_$_TBUF__Y_4_E_SB_LUT4_O_I3 [1:0] = { route_sel[54], route_sel[55] };
  assign \south_$_TBUF__Y_4_E_SB_LUT4_O_I3 [1:0] = { route_sel[54], route_sel[55] };
  assign \south_$_TBUF__Y_E_SB_LUT4_O_I3 [1:0] = { route_sel[22], route_sel[23] };
  assign \north_$_TBUF__Y_E_SB_LUT4_O_I3 [1:0] = { route_sel[22], route_sel[23] };
  assign \north_$_TBUF__Y_1_E_SB_LUT4_O_I3 [1:0] = { route_sel[14], route_sel[15] };
  assign \west_$_TBUF__Y_2_E_SB_LUT4_O_I3 [1:0] = { route_sel[60], route_sel[61] };
  assign \north_$_TBUF__Y_3_E_SB_LUT4_O_I3 [1:0] = { route_sel[62], route_sel[63] };
  assign wire_bus_SB_LUT4_O_6_I1_SB_LUT4_O_2_I2[0] = east[1];
  assign \west_$_TBUF__Y_7_E_SB_LUT4_O_I3 [1:0] = { route_sel[20], route_sel[21] };
  assign \east_$_TBUF__Y_6_E_SB_LUT4_O_I3 [1:0] = { route_sel[38], route_sel[39] };
  assign \east_$_TBUF__Y_E_SB_LUT4_O_I3 [1:0] = { route_sel[22], route_sel[23] };
  assign \west_$_TBUF__Y_E_SB_LUT4_O_I3 [1:0] = { route_sel[12], route_sel[13] };
  assign \east_$_TBUF__Y_1_E_SB_LUT4_O_I3 [1:0] = { route_sel[14], route_sel[15] };
  assign \west_$_TBUF__Y_1_E_SB_LUT4_O_I3 [1:0] = { route_sel[4], route_sel[5] };
  assign \east_$_TBUF__Y_2_E_SB_LUT4_O_I3 [1:0] = { route_sel[6], route_sel[7] };
  assign \north_$_TBUF__Y_2_E_SB_LUT4_O_I3 [1:0] = { route_sel[6], route_sel[7] };
  assign \east_$_TBUF__Y_3_E_SB_LUT4_O_I3 [1:0] = { route_sel[62], route_sel[63] };
  assign \west_$_TBUF__Y_3_E_SB_LUT4_O_I3 [1:0] = { route_sel[52], route_sel[53] };
  assign \south_$_TBUF__Y_2_E_SB_LUT4_O_I3 [1:0] = { route_sel[6], route_sel[7] };
  assign wire_bus_SB_LUT4_O_4_I0[2:0] = { east[3], route_sel[24], route_sel[25] };
  assign wire_bus_SB_LUT4_O_2_I0[2:0] = { east[5], route_sel[40], route_sel[41] };
  assign wire_bus_SB_LUT4_O_2_I0_SB_LUT4_I3_O[0] = wire_bus_SB_LUT4_O_2_I0[3];
  assign wire_bus_SB_LUT4_O_3_I0[2:0] = { east[4], route_sel[32], route_sel[33] };
  assign wire_bus_SB_LUT4_O_6_I1_SB_LUT4_O_2_I3[2:0] = { wire_bus_SB_LUT4_O_6_I1_SB_LUT4_O_2_I2[1], south[1], west[1] };
  assign wire_bus_SB_LUT4_O_6_I1[0] = north[1];
  assign wire_bus_SB_LUT4_O_I1[0] = north[7];
  assign wire_bus_SB_LUT4_O_1_I0[2:0] = { east[6], route_sel[48], route_sel[49] };
  assign wire_bus_SB_LUT4_O_3_I0_SB_LUT4_I3_O[0] = wire_bus_SB_LUT4_O_3_I0[3];
  assign wire_bus_SB_LUT4_O_4_I0_SB_LUT4_I3_O[0] = wire_bus_SB_LUT4_O_4_I0[3];
  assign wire_bus_SB_LUT4_O_5_I0[2:0] = { east[2], route_sel[16], route_sel[17] };
  assign wire_bus_SB_LUT4_O_5_I0_SB_LUT4_I3_O[0] = wire_bus_SB_LUT4_O_5_I0[3];
  assign wire_bus_SB_LUT4_O_7_I0_SB_LUT4_I3_O[0] = wire_bus_SB_LUT4_O_7_I0[3];
  assign \north_$_TBUF__Y_7_E_SB_LUT4_O_I3 [1:0] = { route_sel[30], route_sel[31] };
  assign \east_$_TBUF__Y_7_E_SB_LUT4_O_I3 [1:0] = { route_sel[30], route_sel[31] };
  assign wire_bus_SB_LUT4_O_1_I0_SB_LUT4_I3_O[0] = wire_bus_SB_LUT4_O_1_I0[3];
  assign \south_$_TBUF__Y_7_E_SB_LUT4_O_I3 [1:0] = { route_sel[30], route_sel[31] };
  assign \west_$_TBUF__Y_6_E_SB_LUT4_O_I3 [1:0] = { route_sel[28], route_sel[29] };
  assign \rot_dir$func$source/wiltonSB.sv:51$4866.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:51$4878.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:51$4890.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:51$4902.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:51$4914.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:51$4926.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:51$4938.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:51$4950.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:52$4867.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:52$4879.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:52$4891.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:52$4903.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:52$4915.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:52$4927.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:52$4939.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:52$4951.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:53$4868.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:53$4880.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:53$4892.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:53$4904.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:53$4916.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:53$4928.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:53$4940.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:53$4952.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:57$4869.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:57$4881.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:57$4893.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:57$4905.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:57$4917.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:57$4929.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:57$4941.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:57$4953.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:58$4870.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:58$4882.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:58$4894.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:58$4906.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:58$4918.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:58$4930.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:58$4942.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:58$4954.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:59$4871.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:59$4883.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:59$4895.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:59$4907.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:59$4919.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:59$4931.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:59$4943.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:59$4955.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:63$4872.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:63$4884.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:63$4896.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:63$4908.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:63$4920.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:63$4932.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:63$4944.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:63$4956.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:64$4873.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:64$4885.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:64$4897.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:64$4909.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:64$4921.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:64$4933.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:64$4945.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:64$4957.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:65$4874.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:65$4886.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:65$4898.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:65$4910.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:65$4922.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:65$4934.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:65$4946.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:65$4958.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:69$4875.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:69$4887.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:69$4899.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:69$4911.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:69$4923.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:69$4935.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:69$4947.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:69$4959.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:70$4876.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:70$4888.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:70$4900.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:70$4912.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:70$4924.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:70$4936.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:70$4948.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:70$4960.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:71$4877.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:71$4889.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:71$4901.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:71$4913.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:71$4925.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:71$4937.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:71$4949.turn  = 2'hx;
  assign \rot_dir$func$source/wiltonSB.sv:71$4961.turn  = 2'hx;
endmodule
